///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginRequest {
/*
{
  "email": "",
  "password": ""
}
*/

  String? email;
  String? password;
  String? playerId;

  LoginRequest({this.email, this.password, this.playerId});
  LoginRequest.fromJson(Map<String, dynamic> json) {
    email = json['email']?.toString();
    password = json['password']?.toString();
    playerId = json['playerId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['email'] = email;
    data['password'] = password;
    // data['playerId'] = playerId;
    return data;
  }
}
