///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginResponseModelVendorDataVendorStatus {
/*
{
  "id": "cfbdd725-0e3c-47bc-063f-08dc1ed751be",
  "value": 1,
  "nameAr": "new",
  "nameEn": "new",
  "optionSetId": "30579b4c-1b54-4464-47d6-08dc1ed73cc8",
  "optionSet": null,
  "color": "#26c756",
  "isDefault": true
}
*/

  String? id;
  String? value;
  String? nameAr;
  String? nameEn;
  String? optionSetId;
  String? optionSet;
  String? color;
  bool? isDefault;

  LoginResponseModelVendorDataVendorStatus({
    this.id,
    this.value,
    this.nameAr,
    this.nameEn,
    this.optionSetId,
    this.optionSet,
    this.color,
    this.isDefault,
  });
  LoginResponseModelVendorDataVendorStatus.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    value = json['value']?.toString();
    nameAr = json['nameAr']?.toString();
    nameEn = json['nameEn']?.toString();
    optionSetId = json['optionSetId']?.toString();
    optionSet = json['optionSet']?.toString();
    color = json['color']?.toString();
    isDefault = json['isDefault'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['value'] = value;
    data['nameAr'] = nameAr;
    data['nameEn'] = nameEn;
    data['optionSetId'] = optionSetId;
    data['optionSet'] = optionSet;
    data['color'] = color;
    data['isDefault'] = isDefault;
    return data;
  }
}

class LoginResponseModelVendorDataOwner {
/*
{
  "id": "54cf8eb1-d34f-4114-8e50-90f797086f6c",
  "firstName": "ahmed",
  "middleName": "ahmed",
  "lastName": "almaz",
  "isActive": true,
  "address": "mansoura",
  "otherPhoneNumber": "",
  "isVendor": true,
  "isAdmin": false,
  "email": "sisven@gmail.com",
  "userName": "sisven@gmail.com",
  "phoneNumer": null,
  "password": null,
  "photoId": null,
  "photo": null,
  "gender": 1,
  "birthDate": null,
  "enableNotification": true,
  "pantsMeasurement": "",
  "coachMeasurement": "",
  "tShirtmeasurement": "",
  "isInfluencer": false,
  "socialLogin": 0,
  "isSocialLogin": false
}
*/

  String? id;
  String? firstName;
  String? middleName;
  String? lastName;
  bool? isActive;
  String? address;
  String? otherPhoneNumber;
  bool? isVendor;
  bool? isAdmin;
  String? email;
  String? userName;
  String? phoneNumer;
  String? password;
  String? photoId;
  String? photo;
  String? gender;
  String? birthDate;
  bool? enableNotification;
  String? pantsMeasurement;
  String? coachMeasurement;
  String? tShirtmeasurement;
  bool? isInfluencer;
  String? socialLogin;
  bool? isSocialLogin;

  LoginResponseModelVendorDataOwner({
    this.id,
    this.firstName,
    this.middleName,
    this.lastName,
    this.isActive,
    this.address,
    this.otherPhoneNumber,
    this.isVendor,
    this.isAdmin,
    this.email,
    this.userName,
    this.phoneNumer,
    this.password,
    this.photoId,
    this.photo,
    this.gender,
    this.birthDate,
    this.enableNotification,
    this.pantsMeasurement,
    this.coachMeasurement,
    this.tShirtmeasurement,
    this.isInfluencer,
    this.socialLogin,
    this.isSocialLogin,
  });
  LoginResponseModelVendorDataOwner.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    firstName = json['firstName']?.toString();
    middleName = json['middleName']?.toString();
    lastName = json['lastName']?.toString();
    isActive = json['isActive'];
    address = json['address']?.toString();
    otherPhoneNumber = json['otherPhoneNumber']?.toString();
    isVendor = json['isVendor'];
    isAdmin = json['isAdmin'];
    email = json['email']?.toString();
    userName = json['userName']?.toString();
    phoneNumer = json['phoneNumer']?.toString();
    password = json['password']?.toString();
    photoId = json['photoId']?.toString();
    photo = json['photo']?.toString();
    gender = json['gender']?.toString();
    birthDate = json['birthDate']?.toString();
    enableNotification = json['enableNotification'];
    pantsMeasurement = json['pantsMeasurement']?.toString();
    coachMeasurement = json['coachMeasurement']?.toString();
    tShirtmeasurement = json['tShirtmeasurement']?.toString();
    isInfluencer = json['isInfluencer'];
    socialLogin = json['socialLogin']?.toString();
    isSocialLogin = json['isSocialLogin'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['firstName'] = firstName;
    data['middleName'] = middleName;
    data['lastName'] = lastName;
    data['isActive'] = isActive;
    data['address'] = address;
    data['otherPhoneNumber'] = otherPhoneNumber;
    data['isVendor'] = isVendor;
    data['isAdmin'] = isAdmin;
    data['email'] = email;
    data['userName'] = userName;
    data['phoneNumer'] = phoneNumer;
    data['password'] = password;
    data['photoId'] = photoId;
    data['photo'] = photo;
    data['gender'] = gender;
    data['birthDate'] = birthDate;
    data['enableNotification'] = enableNotification;
    data['pantsMeasurement'] = pantsMeasurement;
    data['coachMeasurement'] = coachMeasurement;
    data['tShirtmeasurement'] = tShirtmeasurement;
    data['isInfluencer'] = isInfluencer;
    data['socialLogin'] = socialLogin;
    data['isSocialLogin'] = isSocialLogin;
    return data;
  }
}

class LoginResponseModelVendorData {
/*
{
  "id": "f5e3cba2-f9f9-4942-b7b0-08dcb5ded2a3",
  "created": "06-08-2024 16:13:00",
  "isDeleted": false,
  "name": "الماظ ستور",
  "nameEn": "almaz store",
  "description": "الماظ ستور",
  "descriptionEn": "almaz store",
  "ownerName": "ahmed",
  "ownerPhoneNumber": "1014927191",
  "ownerPhoneNumber2": "1555438049",
  "isActive": true,
  "logoId": null,
  "logo": null,
  "banerId": null,
  "baner": null,
  "ownerId": "54cf8eb1-d34f-4114-8e50-90f797086f6c",
  "owner": {
    "id": "54cf8eb1-d34f-4114-8e50-90f797086f6c",
    "firstName": "ahmed",
    "middleName": "ahmed",
    "lastName": "almaz",
    "isActive": true,
    "address": "mansoura",
    "otherPhoneNumber": "",
    "isVendor": true,
    "isAdmin": false,
    "email": "sisven@gmail.com",
    "userName": "sisven@gmail.com",
    "phoneNumer": null,
    "password": null,
    "photoId": null,
    "photo": null,
    "gender": 1,
    "birthDate": null,
    "enableNotification": true,
    "pantsMeasurement": "",
    "coachMeasurement": "",
    "tShirtmeasurement": "",
    "isInfluencer": false,
    "socialLogin": 0,
    "isSocialLogin": false
  },
  "isApproved": true,
  "vendorStatusId": "cfbdd725-0e3c-47bc-063f-08dc1ed751be",
  "vendorStatus": {
    "id": "cfbdd725-0e3c-47bc-063f-08dc1ed751be",
    "value": 1,
    "nameAr": "new",
    "nameEn": "new",
    "optionSetId": "30579b4c-1b54-4464-47d6-08dc1ed73cc8",
    "optionSet": null,
    "color": "#26c756",
    "isDefault": true
  }
}
*/

  String? id;
  String? created;
  bool? isDeleted;
  String? name;
  String? nameEn;
  String? description;
  String? descriptionEn;
  String? ownerName;
  String? ownerPhoneNumber;
  String? ownerPhoneNumber2;
  bool? isActive;
  String? logoId;
  String? logo;
  String? banerId;
  String? baner;
  String? ownerId;
  LoginResponseModelVendorDataOwner? owner;
  bool? isApproved;
  String? vendorStatusId;
  LoginResponseModelVendorDataVendorStatus? vendorStatus;

  LoginResponseModelVendorData({
    this.id,
    this.created,
    this.isDeleted,
    this.name,
    this.nameEn,
    this.description,
    this.descriptionEn,
    this.ownerName,
    this.ownerPhoneNumber,
    this.ownerPhoneNumber2,
    this.isActive,
    this.logoId,
    this.logo,
    this.banerId,
    this.baner,
    this.ownerId,
    this.owner,
    this.isApproved,
    this.vendorStatusId,
    this.vendorStatus,
  });
  LoginResponseModelVendorData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    created = json['created']?.toString();
    isDeleted = json['isDeleted'];
    name = json['name']?.toString();
    nameEn = json['nameEn']?.toString();
    description = json['description']?.toString();
    descriptionEn = json['descriptionEn']?.toString();
    ownerName = json['ownerName']?.toString();
    ownerPhoneNumber = json['ownerPhoneNumber']?.toString();
    ownerPhoneNumber2 = json['ownerPhoneNumber2']?.toString();
    isActive = json['isActive'];
    logoId = json['logoId']?.toString();
    logo = json['logo']?.toString();
    banerId = json['banerId']?.toString();
    baner = json['baner']?.toString();
    ownerId = json['ownerId']?.toString();
    owner = (json['owner'] != null)
        ? LoginResponseModelVendorDataOwner.fromJson(json['owner'])
        : null;
    isApproved = json['isApproved'];
    vendorStatusId = json['vendorStatusId']?.toString();
    vendorStatus = (json['vendorStatus'] != null)
        ? LoginResponseModelVendorDataVendorStatus.fromJson(
            json['vendorStatus'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created'] = created;
    data['isDeleted'] = isDeleted;
    data['name'] = name;
    data['nameEn'] = nameEn;
    data['description'] = description;
    data['descriptionEn'] = descriptionEn;
    data['ownerName'] = ownerName;
    data['ownerPhoneNumber'] = ownerPhoneNumber;
    data['ownerPhoneNumber2'] = ownerPhoneNumber2;
    data['isActive'] = isActive;
    data['logoId'] = logoId;
    data['logo'] = logo;
    data['banerId'] = banerId;
    data['baner'] = baner;
    data['ownerId'] = ownerId;
    if (owner != null) {
      data['owner'] = owner!.toJson();
    }
    data['isApproved'] = isApproved;
    data['vendorStatusId'] = vendorStatusId;
    if (vendorStatus != null) {
      data['vendorStatus'] = vendorStatus!.toJson();
    }
    return data;
  }
}

class LoginResponseModelUser {
/*
{
  "id": "54cf8eb1-d34f-4114-8e50-90f797086f6c",
  "firstName": "ahmed",
  "middleName": "ahmed",
  "lastName": "almaz",
  "isActive": true,
  "address": "mansoura",
  "otherPhoneNumber": "",
  "isVendor": true,
  "isAdmin": false,
  "email": "sisven@gmail.com",
  "userName": "sisven@gmail.com",
  "phoneNumer": null,
  "password": null,
  "photoId": null,
  "photo": null,
  "gender": 1,
  "birthDate": null,
  "enableNotification": true,
  "pantsMeasurement": "",
  "coachMeasurement": "",
  "tShirtmeasurement": "",
  "isInfluencer": false,
  "socialLogin": 0,
  "isSocialLogin": false
}
*/

  String? id;
  String? firstName;
  String? middleName;
  String? lastName;
  bool? isActive;
  String? address;
  String? otherPhoneNumber;
  bool? isVendor;
  bool? isAdmin;
  String? email;
  String? userName;
  String? phoneNumer;
  String? password;
  String? photoId;
  String? photo;
  String? gender;
  String? birthDate;
  bool? enableNotification;
  String? pantsMeasurement;
  String? coachMeasurement;
  String? tShirtmeasurement;
  bool? isInfluencer;
  String? socialLogin;
  bool? isSocialLogin;

  LoginResponseModelUser({
    this.id,
    this.firstName,
    this.middleName,
    this.lastName,
    this.isActive,
    this.address,
    this.otherPhoneNumber,
    this.isVendor,
    this.isAdmin,
    this.email,
    this.userName,
    this.phoneNumer,
    this.password,
    this.photoId,
    this.photo,
    this.gender,
    this.birthDate,
    this.enableNotification,
    this.pantsMeasurement,
    this.coachMeasurement,
    this.tShirtmeasurement,
    this.isInfluencer,
    this.socialLogin,
    this.isSocialLogin,
  });
  LoginResponseModelUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    firstName = json['firstName']?.toString();
    middleName = json['middleName']?.toString();
    lastName = json['lastName']?.toString();
    isActive = json['isActive'];
    address = json['address']?.toString();
    otherPhoneNumber = json['otherPhoneNumber']?.toString();
    isVendor = json['isVendor'];
    isAdmin = json['isAdmin'];
    email = json['email']?.toString();
    userName = json['userName']?.toString();
    phoneNumer = json['phoneNumer']?.toString();
    password = json['password']?.toString();
    photoId = json['photoId']?.toString();
    photo = json['photo']?.toString();
    gender = json['gender']?.toString();
    birthDate = json['birthDate']?.toString();
    enableNotification = json['enableNotification'];
    pantsMeasurement = json['pantsMeasurement']?.toString();
    coachMeasurement = json['coachMeasurement']?.toString();
    tShirtmeasurement = json['tShirtmeasurement']?.toString();
    isInfluencer = json['isInfluencer'];
    socialLogin = json['socialLogin']?.toString();
    isSocialLogin = json['isSocialLogin'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['firstName'] = firstName;
    data['middleName'] = middleName;
    data['lastName'] = lastName;
    data['isActive'] = isActive;
    data['address'] = address;
    data['otherPhoneNumber'] = otherPhoneNumber;
    data['isVendor'] = isVendor;
    data['isAdmin'] = isAdmin;
    data['email'] = email;
    data['userName'] = userName;
    data['phoneNumer'] = phoneNumer;
    data['password'] = password;
    data['photoId'] = photoId;
    data['photo'] = photo;
    data['gender'] = gender;
    data['birthDate'] = birthDate;
    data['enableNotification'] = enableNotification;
    data['pantsMeasurement'] = pantsMeasurement;
    data['coachMeasurement'] = coachMeasurement;
    data['tShirtmeasurement'] = tShirtmeasurement;
    data['isInfluencer'] = isInfluencer;
    data['socialLogin'] = socialLogin;
    data['isSocialLogin'] = isSocialLogin;
    return data;
  }
}

class LoginResponseModel {
/*
{
  "user": {
    "id": "54cf8eb1-d34f-4114-8e50-90f797086f6c",
    "firstName": "ahmed",
    "middleName": "ahmed",
    "lastName": "almaz",
    "isActive": true,
    "address": "mansoura",
    "otherPhoneNumber": "",
    "isVendor": true,
    "isAdmin": false,
    "email": "sisven@gmail.com",
    "userName": "sisven@gmail.com",
    "phoneNumer": null,
    "password": null,
    "photoId": null,
    "photo": null,
    "gender": 1,
    "birthDate": null,
    "enableNotification": true,
    "pantsMeasurement": "",
    "coachMeasurement": "",
    "tShirtmeasurement": "",
    "isInfluencer": false,
    "socialLogin": 0,
    "isSocialLogin": false
  },
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoic2lzdmVuQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNTRjZjhlYjEtZDM0Zi00MTE0LThlNTAtOTBmNzk3MDg2ZjZjIiwiZXhwIjoxNzI1NTE4MDk0LCJpc3MiOiJTaXNsaW1vZGEiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo0NDMxMiJ9._PFU_GNv4P4YufFIZYEzMwb7LMYyIKDvYlOxlEOVJvE",
  "vendorData": {
    "id": "f5e3cba2-f9f9-4942-b7b0-08dcb5ded2a3",
    "created": "06-08-2024 16:13:00",
    "isDeleted": false,
    "name": "الماظ ستور",
    "nameEn": "almaz store",
    "description": "الماظ ستور",
    "descriptionEn": "almaz store",
    "ownerName": "ahmed",
    "ownerPhoneNumber": "1014927191",
    "ownerPhoneNumber2": "1555438049",
    "isActive": true,
    "logoId": null,
    "logo": null,
    "banerId": null,
    "baner": null,
    "ownerId": "54cf8eb1-d34f-4114-8e50-90f797086f6c",
    "owner": {
      "id": "54cf8eb1-d34f-4114-8e50-90f797086f6c",
      "firstName": "ahmed",
      "middleName": "ahmed",
      "lastName": "almaz",
      "isActive": true,
      "address": "mansoura",
      "otherPhoneNumber": "",
      "isVendor": true,
      "isAdmin": false,
      "email": "sisven@gmail.com",
      "userName": "sisven@gmail.com",
      "phoneNumer": null,
      "password": null,
      "photoId": null,
      "photo": null,
      "gender": 1,
      "birthDate": null,
      "enableNotification": true,
      "pantsMeasurement": "",
      "coachMeasurement": "",
      "tShirtmeasurement": "",
      "isInfluencer": false,
      "socialLogin": 0,
      "isSocialLogin": false
    },
    "isApproved": true,
    "vendorStatusId": "cfbdd725-0e3c-47bc-063f-08dc1ed751be",
    "vendorStatus": {
      "id": "cfbdd725-0e3c-47bc-063f-08dc1ed751be",
      "value": 1,
      "nameAr": "new",
      "nameEn": "new",
      "optionSetId": "30579b4c-1b54-4464-47d6-08dc1ed73cc8",
      "optionSet": null,
      "color": "#26c756",
      "isDefault": true
    }
  }
}
*/

  LoginResponseModelUser? user;
  String? token;
  LoginResponseModelVendorData? vendorData;

  LoginResponseModel({
    this.user,
    this.token,
    this.vendorData,
  });
  LoginResponseModel.fromJson(Map<String, dynamic> json) {
    user = (json['user'] != null)
        ? LoginResponseModelUser.fromJson(json['user'])
        : null;
    token = json['token']?.toString();
    vendorData = (json['vendorData'] != null)
        ? LoginResponseModelVendorData.fromJson(json['vendorData'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['token'] = token;
    if (vendorData != null) {
      data['vendorData'] = vendorData!.toJson();
    }
    return data;
  }
}
