///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SendVerifyCode {
/*
{
  "userName": "widget.email",
  "code": "otpController"
}
*/

  String? userName;
  String? code;
  Map<String, dynamic> __origJson = {};

  SendVerifyCode({
    this.userName,
    this.code,
  });
  SendVerifyCode.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    userName = json['userName']?.toString();
    code = json['code']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userName'] = userName;
    data['code'] = code;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
