///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SetNewPasswordModel {
/*
{
  "userId": "string",
  "newpassword": "string"
}
*/

  String? userId;
  String? newpassword;
  Map<String, dynamic> __origJson = {};

  SetNewPasswordModel({
    this.userId,
    this.newpassword,
  });
  SetNewPasswordModel.fromJson(Map<String, dynamic> json) {
    __origJson = json;
    userId = json['userId']?.toString();
    newpassword = json['newpassword']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userId'] = userId;
    data['newpassword'] = newpassword;
    return data;
  }

  Map<String, dynamic> origJson() => __origJson;
}
