///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VendorModelVendorStatus {
/*
{
  "id": "3f5d02b9-fc7e-461a-7c68-08dc244cd578",
  "value": 3,
  "nameAr": "مقبول",
  "nameEn": "Accepted",
  "optionSetId": "30579b4c-1b54-4464-47d6-08dc1ed73cc8",
  "optionSet": null,
  "color": "#64f198",
  "isDefault": true
}
*/

  String? id;
  String? value;
  String? nameAr;
  String? nameEn;
  String? optionSetId;
  String? optionSet;
  String? color;
  bool? isDefault;

  VendorModelVendorStatus({
    this.id,
    this.value,
    this.nameAr,
    this.nameEn,
    this.optionSetId,
    this.optionSet,
    this.color,
    this.isDefault,
  });
  VendorModelVendorStatus.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    value = json['value']?.toString();
    nameAr = json['nameAr']?.toString();
    nameEn = json['nameEn']?.toString();
    optionSetId = json['optionSetId']?.toString();
    optionSet = json['optionSet']?.toString();
    color = json['color']?.toString();
    isDefault = json['isDefault'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['value'] = value;
    data['nameAr'] = nameAr;
    data['nameEn'] = nameEn;
    data['optionSetId'] = optionSetId;
    data['optionSet'] = optionSet;
    data['color'] = color;
    data['isDefault'] = isDefault;
    return data;
  }
}

class VendorModelOwner {
/*
{
  "id": "16cb227b-43c6-491c-bcb9-c7c3024f2483",
  "firstName": "ahmed",
  "middleName": "ahmed ",
  "lastName": "almaz",
  "isActive": true,
  "address": "amr ebn elass",
  "otherPhoneNumber": "",
  "isVendor": true,
  "isAdmin": false,
  "email": "sislimodavendor@gmail.com",
  "userName": "sislimodavendor@gmail.com",
  "phoneNumer": null,
  "photoId": "240a2f89-2743-40a1-b8fa-443cb8caf8c9",
  "photo": null,
  "gender": 1,
  "birthDate": null,
  "photoUrl": null,
  "enableNotification": true,
  "pantsMeasurement": "",
  "coachMeasurement": "",
  "tShirtmeasurement": "",
  "isInfluencer": false,
  "socialLogin": 0,
  "isSocialLogin": false
}
*/

  String? id;
  String? firstName;
  String? middleName;
  String? lastName;
  bool? isActive;
  String? address;
  String? otherPhoneNumber;
  bool? isVendor;
  bool? isAdmin;
  String? email;
  String? userName;
  String? phoneNumer;
  String? photoId;
  String? photo;
  String? gender;
  String? birthDate;
  String? photoUrl;
  bool? enableNotification;
  String? pantsMeasurement;
  String? coachMeasurement;
  String? tShirtmeasurement;
  bool? isInfluencer;
  String? socialLogin;
  bool? isSocialLogin;

  VendorModelOwner({
    this.id,
    this.firstName,
    this.middleName,
    this.lastName,
    this.isActive,
    this.address,
    this.otherPhoneNumber,
    this.isVendor,
    this.isAdmin,
    this.email,
    this.userName,
    this.phoneNumer,
    this.photoId,
    this.photo,
    this.gender,
    this.birthDate,
    this.photoUrl,
    this.enableNotification,
    this.pantsMeasurement,
    this.coachMeasurement,
    this.tShirtmeasurement,
    this.isInfluencer,
    this.socialLogin,
    this.isSocialLogin,
  });
  VendorModelOwner.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    firstName = json['firstName']?.toString();
    middleName = json['middleName']?.toString();
    lastName = json['lastName']?.toString();
    isActive = json['isActive'];
    address = json['address']?.toString();
    otherPhoneNumber = json['otherPhoneNumber']?.toString();
    isVendor = json['isVendor'];
    isAdmin = json['isAdmin'];
    email = json['email']?.toString();
    userName = json['userName']?.toString();
    phoneNumer = json['phoneNumer']?.toString();
    photoId = json['photoId']?.toString();
    photo = json['photo']?.toString();
    gender = json['gender']?.toString();
    birthDate = json['birthDate']?.toString();
    photoUrl = json['photoUrl']?.toString();
    enableNotification = json['enableNotification'];
    pantsMeasurement = json['pantsMeasurement']?.toString();
    coachMeasurement = json['coachMeasurement']?.toString();
    tShirtmeasurement = json['tShirtmeasurement']?.toString();
    isInfluencer = json['isInfluencer'];
    socialLogin = json['socialLogin']?.toString();
    isSocialLogin = json['isSocialLogin'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['firstName'] = firstName;
    data['middleName'] = middleName;
    data['lastName'] = lastName;
    data['isActive'] = isActive;
    data['address'] = address;
    data['otherPhoneNumber'] = otherPhoneNumber;
    data['isVendor'] = isVendor;
    data['isAdmin'] = isAdmin;
    data['email'] = email;
    data['userName'] = userName;
    data['phoneNumer'] = phoneNumer;
    data['photoId'] = photoId;
    data['photo'] = photo;
    data['gender'] = gender;
    data['birthDate'] = birthDate;
    data['photoUrl'] = photoUrl;
    data['enableNotification'] = enableNotification;
    data['pantsMeasurement'] = pantsMeasurement;
    data['coachMeasurement'] = coachMeasurement;
    data['tShirtmeasurement'] = tShirtmeasurement;
    data['isInfluencer'] = isInfluencer;
    data['socialLogin'] = socialLogin;
    data['isSocialLogin'] = isSocialLogin;
    return data;
  }
}

class VendorModelBaner {
/*
{
  "id": "7d1ec66c-54cd-4e93-ac4b-c35a4e45c6fb",
  "imageId": "8c985e78-bd91-4fa0-80e8-3e178281216c",
  "name": "8c985e78-bd91-4fa0-80e8-3e178281216c.jpg",
  "fullLink": "https://sislimoda.com/Files/8c985e78-bd91-4fa0-80e8-3e178281216c.jpg"
}
*/

  String? id;
  String? imageId;
  String? name;
  String? fullLink;

  VendorModelBaner({
    this.id,
    this.imageId,
    this.name,
    this.fullLink,
  });
  VendorModelBaner.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    imageId = json['imageId']?.toString();
    name = json['name']?.toString();
    fullLink = json['fullLink']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['imageId'] = imageId;
    data['name'] = name;
    data['fullLink'] = fullLink;
    return data;
  }
}

class VendorModelLogo {
/*
{
  "id": "7d1ec66c-54cd-4e93-ac4b-c35a4e45c6fb",
  "imageId": "8c985e78-bd91-4fa0-80e8-3e178281216c",
  "name": "8c985e78-bd91-4fa0-80e8-3e178281216c.jpg",
  "fullLink": "https://sislimoda.com/Files/8c985e78-bd91-4fa0-80e8-3e178281216c.jpg"
}
*/

  String? id;
  String? imageId;
  String? name;
  String? fullLink;

  VendorModelLogo({
    this.id,
    this.imageId,
    this.name,
    this.fullLink,
  });
  VendorModelLogo.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    imageId = json['imageId']?.toString();
    name = json['name']?.toString();
    fullLink = json['fullLink']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['imageId'] = imageId;
    data['name'] = name;
    data['fullLink'] = fullLink;
    return data;
  }
}

class VendorModel {
/*
{
  "id": "0fd4806d-e6e6-48df-7b91-08dc1ed95a1b",
  "created": "27-01-2024 12:21:25",
  "isDeleted": false,
  "name": "بوما",
  "nameEn": "Puma11",
  "description": "بوما هي علامة تجارية عالمية للملابس الرياضية معروفة بأحذيتها الرياضية عالية الأداء وملابسها وإكسسواراتها، حيث تجمع بين الأناقة والابتكار.",
  "descriptionEn": "Puma is a global sportswear brand known for its high-performance athletic shoes, apparel, and accessories, blending style with innovation.",
  "ownerName": null,
  "ownerPhoneNumber": "01014927191",
  "ownerPhoneNumber2": "0155543804",
  "isActive": true,
  "logoId": "7d1ec66c-54cd-4e93-ac4b-c35a4e45c6fb",
  "logo": {
    "id": "7d1ec66c-54cd-4e93-ac4b-c35a4e45c6fb",
    "imageId": "8c985e78-bd91-4fa0-80e8-3e178281216c",
    "name": "8c985e78-bd91-4fa0-80e8-3e178281216c.jpg",
    "fullLink": "https://sislimoda.com/Files/8c985e78-bd91-4fa0-80e8-3e178281216c.jpg"
  },
  "banerId": "7d1ec66c-54cd-4e93-ac4b-c35a4e45c6fb",
  "baner": {
    "id": "7d1ec66c-54cd-4e93-ac4b-c35a4e45c6fb",
    "imageId": "8c985e78-bd91-4fa0-80e8-3e178281216c",
    "name": "8c985e78-bd91-4fa0-80e8-3e178281216c.jpg",
    "fullLink": "https://sislimoda.com/Files/8c985e78-bd91-4fa0-80e8-3e178281216c.jpg"
  },
  "ownerId": "16cb227b-43c6-491c-bcb9-c7c3024f2483",
  "owner": {
    "id": "16cb227b-43c6-491c-bcb9-c7c3024f2483",
    "firstName": "ahmed",
    "middleName": "ahmed ",
    "lastName": "almaz",
    "isActive": true,
    "address": "amr ebn elass",
    "otherPhoneNumber": "",
    "isVendor": true,
    "isAdmin": false,
    "email": "sislimodavendor@gmail.com",
    "userName": "sislimodavendor@gmail.com",
    "phoneNumer": null,
    "photoId": "240a2f89-2743-40a1-b8fa-443cb8caf8c9",
    "photo": null,
    "gender": 1,
    "birthDate": null,
    "photoUrl": null,
    "enableNotification": true,
    "pantsMeasurement": "",
    "coachMeasurement": "",
    "tShirtmeasurement": "",
    "isInfluencer": false,
    "socialLogin": 0,
    "isSocialLogin": false
  },
  "isApproved": true,
  "vendorStatusId": "3f5d02b9-fc7e-461a-7c68-08dc244cd578",
  "vendorStatus": {
    "id": "3f5d02b9-fc7e-461a-7c68-08dc244cd578",
    "value": 3,
    "nameAr": "مقبول",
    "nameEn": "Accepted",
    "optionSetId": "30579b4c-1b54-4464-47d6-08dc1ed73cc8",
    "optionSet": null,
    "color": "#64f198",
    "isDefault": true
  },
  "isStore": false,
  "isPreferred": false,
  "companyName": null,
  "fullCompanyAddress": null,
  "numberOfProductsToSell": 0,
  "workFields": null,
  "workFieldsList": [
    null
  ],
  "bankNumber": null,
  "iban": null,
  "bankName": null,
  "vendorCompanyAttachments": [
    null
  ]
}
*/

  String? id;
  String? created;
  bool? isDeleted;
  String? name;
  String? nameEn;
  String? description;
  String? descriptionEn;
  String? ownerName;
  String? ownerPhoneNumber;
  String? ownerPhoneNumber2;
  bool? isActive;
  String? logoId;
  VendorModelLogo? logo;
  String? banerId;
  VendorModelBaner? baner;
  String? ownerId;
  VendorModelOwner? owner;
  bool? isApproved;
  String? vendorStatusId;
  VendorModelVendorStatus? vendorStatus;
  bool? isStore;
  bool? isPreferred;
  String? companyName;
  String? fullCompanyAddress;
  String? numberOfProductsToSell;
  String? workFields;
  List<String?>? workFieldsList;
  String? bankNumber;
  String? iban;
  String? bankName;
  List<String?>? vendorCompanyAttachments;

  VendorModel({
    this.id,
    this.created,
    this.isDeleted,
    this.name,
    this.nameEn,
    this.description,
    this.descriptionEn,
    this.ownerName,
    this.ownerPhoneNumber,
    this.ownerPhoneNumber2,
    this.isActive,
    this.logoId,
    this.logo,
    this.banerId,
    this.baner,
    this.ownerId,
    this.owner,
    this.isApproved,
    this.vendorStatusId,
    this.vendorStatus,
    this.isStore,
    this.isPreferred,
    this.companyName,
    this.fullCompanyAddress,
    this.numberOfProductsToSell,
    this.workFields,
    this.workFieldsList,
    this.bankNumber,
    this.iban,
    this.bankName,
    this.vendorCompanyAttachments,
  });
  VendorModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    created = json['created']?.toString();
    isDeleted = json['isDeleted'];
    name = json['name']?.toString();
    nameEn = json['nameEn']?.toString();
    description = json['description']?.toString();
    descriptionEn = json['descriptionEn']?.toString();
    ownerName = json['ownerName']?.toString();
    ownerPhoneNumber = json['ownerPhoneNumber']?.toString();
    ownerPhoneNumber2 = json['ownerPhoneNumber2']?.toString();
    isActive = json['isActive'];
    logoId = json['logoId']?.toString();
    logo =
        (json['logo'] != null) ? VendorModelLogo.fromJson(json['logo']) : null;
    banerId = json['banerId']?.toString();
    baner = (json['baner'] != null)
        ? VendorModelBaner.fromJson(json['baner'])
        : null;
    ownerId = json['ownerId']?.toString();
    owner = (json['owner'] != null)
        ? VendorModelOwner.fromJson(json['owner'])
        : null;
    isApproved = json['isApproved'];
    vendorStatusId = json['vendorStatusId']?.toString();
    vendorStatus = (json['vendorStatus'] != null)
        ? VendorModelVendorStatus.fromJson(json['vendorStatus'])
        : null;
    isStore = json['isStore'];
    isPreferred = json['isPreferred'];
    companyName = json['companyName']?.toString();
    fullCompanyAddress = json['fullCompanyAddress']?.toString();
    numberOfProductsToSell = json['numberOfProductsToSell']?.toString();
    workFields = json['workFields']?.toString();
    bankNumber = json['bankNumber']?.toString();
    iban = json['iban']?.toString();
    bankName = json['bankName']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['created'] = created;
    data['isDeleted'] = isDeleted;
    data['name'] = name;
    data['nameEn'] = nameEn;
    data['description'] = description;
    data['descriptionEn'] = descriptionEn;
    data['ownerName'] = ownerName;
    data['ownerPhoneNumber'] = ownerPhoneNumber;
    data['ownerPhoneNumber2'] = ownerPhoneNumber2;
    data['isActive'] = isActive;
    data['logoId'] = logoId;
    if (logo != null) {
      data['logo'] = logo!.toJson();
    }
    data['banerId'] = banerId;
    if (baner != null) {
      data['baner'] = baner!.toJson();
    }
    data['ownerId'] = ownerId;
    if (owner != null) {
      data['owner'] = owner!.toJson();
    }
    data['isApproved'] = isApproved;
    data['vendorStatusId'] = vendorStatusId;
    if (vendorStatus != null) {
      data['vendorStatus'] = vendorStatus!.toJson();
    }
    data['isStore'] = isStore;
    data['isPreferred'] = isPreferred;
    data['companyName'] = companyName;
    data['fullCompanyAddress'] = fullCompanyAddress;
    data['numberOfProductsToSell'] = numberOfProductsToSell;
    data['workFields'] = workFields;
    data['bankNumber'] = bankNumber;
    data['iban'] = iban;
    data['bankName'] = bankName;
    return data;
  }
}
