name: sislimoda_admin_dashboard
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.6
  fl_chart: ^0.66.0
  translator: ^1.0.3+1
  auto_route: ^8.1.4
  bloc: ^8.1.2
  cached_network_image: ^3.4.1
  flutter_pagination: ^0.0.8
  country_code_picker: ^3.0.0
  dio: ^5.6.0
  flutter_rating_bar: ^4.0.1
  pin_code_text_field: ^1.8.0

  cupertino_icons: ^1.0.2
  animated_rating_stars: ^1.0.1
  dartz: ^0.10.1
  dropdown_button2: ^2.3.9
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  extended_phone_number_input: ^1.0.2
  image_network: ^2.5.6
  easy_stepper: ^0.8.5
  flutter_bloc: ^8.1.3
  pie_chart: ^5.4.0
  flutter_i18n: null
  intl_translation: ^0.20.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_svg: any
  get: ^4.6.5
  http: ^1.1.0
  intl: ^0.20.2
  easy_localization: ^3.0.4
  number_pagination: ^1.0.7
  flutter_date_range_picker: 0.2.1
  shared_preferences: ^2.2.0
  google_fonts: ^6.1.0
  jwt_decoder: ^2.0.1
#  syncfusion_flutter_charts:
  data_table_2: ^2.5.10
  dotted_border: ^2.1.0
  image_picker: ^1.0.7
  multi_dropdown: ^2.1.4
  loading_indicator: ^3.1.1
  flex_color_picker: ^3.6.0
  country_picker: ^2.0.26
  audioplayers: ^5.2.1
  file_picker: ^10.2.0
  syncfusion_flutter_charts: ^30.1.40
dev_dependencies:
  auto_route_generator:
  build_runner: ^2.4.4
  



  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true

  assets:
    - asset/images/
    - asset/translations/
    - assets/sounds/


