import 'dart:convert';

import 'package:sislimoda_admin_dashboard/models/product/product_model.dart';

List<OrderModel> orderModelModelFromJson(String str) =>
    List<OrderModel>.from(json.decode(str).map((x) => OrderModel.fromJson(x)));

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class OrderModelOrderProductsUser {
/*
{
  "id": "1da8eac9-006a-4841-9fcd-bba67b258067",
  "firstName": "ahmed",
  "middleName": "",
  "lastName": "almaz",
  "isActive": true,
  "address": "",
  "otherPhoneNumber": "",
  "isVendor": false,
  "isAdmin": false,
  "email": "a.almaz826@gmail.com",
  "userName": "a.almaz826@gmail.com",
  "phoneNumer": "99585048",
  "password": null,
  "photoId": null,
  "photo": null,
  "gender": 0,
  "birthDate": "1/1/0001 12:00:00 AM",
  "enableNotification": true,
  "pantsMeasurement": "",
  "coachMeasurement": "",
  "tShirtmeasurement": "XS",
  "isInfluencer": false,
  "socialLogin": 0,
  "isSocialLogin": false
}
*/

  String? id;
  String? firstName;
  String? middleName;
  String? lastName;
  bool? isActive;
  String? address;
  String? otherPhoneNumber;
  bool? isVendor;
  bool? isAdmin;
  String? email;
  String? userName;
  String? phoneNumer;
  String? password;
  String? photoId;
  String? photo;
  String? gender;
  String? birthDate;
  bool? enableNotification;
  String? pantsMeasurement;
  String? coachMeasurement;
  String? tShirtmeasurement;
  bool? isInfluencer;
  String? socialLogin;
  bool? isSocialLogin;

  OrderModelOrderProductsUser({
    this.id,
    this.firstName,
    this.middleName,
    this.lastName,
    this.isActive,
    this.address,
    this.otherPhoneNumber,
    this.isVendor,
    this.isAdmin,
    this.email,
    this.userName,
    this.phoneNumer,
    this.password,
    this.photoId,
    this.photo,
    this.gender,
    this.birthDate,
    this.enableNotification,
    this.pantsMeasurement,
    this.coachMeasurement,
    this.tShirtmeasurement,
    this.isInfluencer,
    this.socialLogin,
    this.isSocialLogin,
  });
  OrderModelOrderProductsUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    firstName = json['firstName']?.toString();
    middleName = json['middleName']?.toString();
    lastName = json['lastName']?.toString();
    isActive = json['isActive'];
    address = json['address']?.toString();
    otherPhoneNumber = json['otherPhoneNumber']?.toString();
    isVendor = json['isVendor'];
    isAdmin = json['isAdmin'];
    email = json['email']?.toString();
    userName = json['userName']?.toString();
    phoneNumer = json['phoneNumer']?.toString();
    password = json['password']?.toString();
    photoId = json['photoId']?.toString();
    photo = json['photo']?.toString();
    gender = json['gender']?.toString();
    birthDate = json['birthDate']?.toString();
    enableNotification = json['enableNotification'];
    pantsMeasurement = json['pantsMeasurement']?.toString();
    coachMeasurement = json['coachMeasurement']?.toString();
    tShirtmeasurement = json['tShirtmeasurement']?.toString();
    isInfluencer = json['isInfluencer'];
    socialLogin = json['socialLogin']?.toString();
    isSocialLogin = json['isSocialLogin'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['firstName'] = firstName;
    data['middleName'] = middleName;
    data['lastName'] = lastName;
    data['isActive'] = isActive;
    data['address'] = address;
    data['otherPhoneNumber'] = otherPhoneNumber;
    data['isVendor'] = isVendor;
    data['isAdmin'] = isAdmin;
    data['email'] = email;
    data['userName'] = userName;
    data['phoneNumer'] = phoneNumer;
    data['password'] = password;
    data['photoId'] = photoId;
    data['photo'] = photo;
    data['gender'] = gender;
    data['birthDate'] = birthDate;
    data['enableNotification'] = enableNotification;
    data['pantsMeasurement'] = pantsMeasurement;
    data['coachMeasurement'] = coachMeasurement;
    data['tShirtmeasurement'] = tShirtmeasurement;
    data['isInfluencer'] = isInfluencer;
    data['socialLogin'] = socialLogin;
    data['isSocialLogin'] = isSocialLogin;
    return data;
  }
}

class OrderModelOrderProductsProductDefaultPhoto {
/*
{
  "id": "a0c4fb82-f403-4809-928d-0ae09428a04d",
  "imageId": "91f4c87d-6540-46fe-83f4-bc90ed624968",
  "name": "91f4c87d-6540-46fe-83f4-bc90ed624968.jpg",
  "fullLink": "https://sislimoda.com/Files/91f4c87d-6540-46fe-83f4-bc90ed624968.jpg"
}
*/

  String? id;
  String? imageId;
  String? name;
  String? fullLink;

  OrderModelOrderProductsProductDefaultPhoto({
    this.id,
    this.imageId,
    this.name,
    this.fullLink,
  });
  OrderModelOrderProductsProductDefaultPhoto.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    imageId = json['imageId']?.toString();
    name = json['name']?.toString();
    fullLink = json['fullLink']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['imageId'] = imageId;
    data['name'] = name;
    data['fullLink'] = fullLink;
    return data;
  }
}

class OrderModelOrderProductsProduct {
/*
{
  "id": "b63ceb4e-8492-446c-54dd-08dc3db67684",
  "name": " أديداس أوريجينالز",
  "nameEn": "Adidas Originals",
  "description": " أديداس أوريجينالز",
  "descriptionEn": "Adidas Originals",
  "defaultPrice": 100,
  "oldPrice": 0,
  "orderNUmber": 0,
  "htmlDescriptions": "string",
  "htmlOther": "string",
  "isActive": true,
  "defaultPhotoId": "a0c4fb82-f403-4809-928d-0ae09428a04d",
  "defaultPhoto": {
    "id": "a0c4fb82-f403-4809-928d-0ae09428a04d",
    "imageId": "91f4c87d-6540-46fe-83f4-bc90ed624968",
    "name": "91f4c87d-6540-46fe-83f4-bc90ed624968.jpg",
    "fullLink": "https://sislimoda.com/Files/91f4c87d-6540-46fe-83f4-bc90ed624968.jpg"
  },
  "categoryId": "56e0235c-532b-409f-8784-08dc1e165a43",
  "vendorId": "0fd4806d-e6e6-48df-7b91-08dc1ed95a1b",
  "amount": 50,
  "brandId": "ff6982b0-f2e8-47c6-0ed6-08dc1e1a7720",
  "brand": null,
  "paymentType": "string",
  "noteForReturn": "string",
  "created": "06-03-2024 18:32:50",
  "category": null,
  "productImages": [
    null
  ],
  "productOptions": [
    null
  ],
  "productDetails": [
    null
  ],
  "isFavourite": false,
  "productPrice": 0,
  "programDiscountPercentage": 0,
  "programDiscountValue": 0,
  "priceAfterProgramInfluencer": 0,
  "influencerPercentage": 0,
  "influencerValue": 0,
  "priceWithInfluencer": 0,
  "maxDiscountWithFamous": 0,
  "productDiscountPercentage": 0,
  "productDiscountValue": 0,
  "priceBeforeDiscount": 0,
  "maxProgramDiscountPercentage": 0,
  "finalDisplayPrice": 0,
  "offers": null,
  "discountPercentage": 0
}
*/

  String? id;
  String? name;
  String? nameEn;
  String? description;
  String? descriptionEn;
  String? defaultPrice;
  String? oldPrice;
  String? orderNUmber;
  String? htmlDescriptions;
  String? htmlOther;
  bool? isActive;
  String? defaultPhotoId;
  OrderModelOrderProductsProductDefaultPhoto? defaultPhoto;
  String? categoryId;
  String? vendorId;
  String? amount;
  String? brandId;
  String? brand;
  String? paymentType;
  String? noteForReturn;
  String? created;
  String? category;
  List<String?>? productImages;
  List<String?>? productOptions;
  List<String?>? productDetails;
  bool? isFavourite;
  String? productPrice;
  String? programDiscountPercentage;
  String? programDiscountValue;
  String? priceAfterProgramInfluencer;
  String? influencerPercentage;
  String? influencerValue;
  String? priceWithInfluencer;
  String? maxDiscountWithFamous;
  String? productDiscountPercentage;
  String? productDiscountValue;
  String? priceBeforeDiscount;
  String? maxProgramDiscountPercentage;
  String? finalDisplayPrice;
  String? offers;
  String? discountPercentage;

  OrderModelOrderProductsProduct({
    this.id,
    this.name,
    this.nameEn,
    this.description,
    this.descriptionEn,
    this.defaultPrice,
    this.oldPrice,
    this.orderNUmber,
    this.htmlDescriptions,
    this.htmlOther,
    this.isActive,
    this.defaultPhotoId,
    this.defaultPhoto,
    this.categoryId,
    this.vendorId,
    this.amount,
    this.brandId,
    this.brand,
    this.paymentType,
    this.noteForReturn,
    this.created,
    this.category,
    this.productImages,
    this.productOptions,
    this.productDetails,
    this.isFavourite,
    this.productPrice,
    this.programDiscountPercentage,
    this.programDiscountValue,
    this.priceAfterProgramInfluencer,
    this.influencerPercentage,
    this.influencerValue,
    this.priceWithInfluencer,
    this.maxDiscountWithFamous,
    this.productDiscountPercentage,
    this.productDiscountValue,
    this.priceBeforeDiscount,
    this.maxProgramDiscountPercentage,
    this.finalDisplayPrice,
    this.offers,
    this.discountPercentage,
  });
  OrderModelOrderProductsProduct.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    nameEn = json['nameEn']?.toString();
    description = json['description']?.toString();
    descriptionEn = json['descriptionEn']?.toString();
    defaultPrice = json['defaultPrice']?.toString();
    oldPrice = json['oldPrice']?.toString();
    orderNUmber = json['orderNUmber']?.toString();
    htmlDescriptions = json['htmlDescriptions']?.toString();
    htmlOther = json['htmlOther']?.toString();
    isActive = json['isActive'];
    defaultPhotoId = json['defaultPhotoId']?.toString();
    defaultPhoto = (json['defaultPhoto'] != null)
        ? OrderModelOrderProductsProductDefaultPhoto.fromJson(
            json['defaultPhoto'])
        : null;
    categoryId = json['categoryId']?.toString();
    vendorId = json['vendorId']?.toString();
    amount = json['amount']?.toString();
    brandId = json['brandId']?.toString();
    brand = json['brand']?.toString();
    paymentType = json['paymentType']?.toString();
    noteForReturn = json['noteForReturn']?.toString();
    created = json['created']?.toString();
    category = json['category']?.toString();

    isFavourite = json['isFavourite'];
    productPrice = json['productPrice']?.toString();
    programDiscountPercentage = json['programDiscountPercentage']?.toString();
    programDiscountValue = json['programDiscountValue']?.toString();
    priceAfterProgramInfluencer =
        json['priceAfterProgramInfluencer']?.toString();
    influencerPercentage = json['influencerPercentage']?.toString();
    influencerValue = json['influencerValue']?.toString();
    priceWithInfluencer = json['priceWithInfluencer']?.toString();
    maxDiscountWithFamous = json['maxDiscountWithFamous']?.toString();
    productDiscountPercentage = json['productDiscountPercentage']?.toString();
    productDiscountValue = json['productDiscountValue']?.toString();
    priceBeforeDiscount = json['priceBeforeDiscount']?.toString();
    maxProgramDiscountPercentage =
        json['maxProgramDiscountPercentage']?.toString();
    finalDisplayPrice = json['finalDisplayPrice']?.toString();
    offers = json['offers']?.toString();
    discountPercentage = json['discountPercentage']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['nameEn'] = nameEn;
    data['description'] = description;
    data['descriptionEn'] = descriptionEn;
    data['defaultPrice'] = defaultPrice;
    data['oldPrice'] = oldPrice;
    data['orderNUmber'] = orderNUmber;
    data['htmlDescriptions'] = htmlDescriptions;
    data['htmlOther'] = htmlOther;
    data['isActive'] = isActive;
    data['defaultPhotoId'] = defaultPhotoId;
    if (defaultPhoto != null) {
      data['defaultPhoto'] = defaultPhoto!.toJson();
    }
    data['categoryId'] = categoryId;
    data['vendorId'] = vendorId;
    data['amount'] = amount;
    data['brandId'] = brandId;
    data['brand'] = brand;
    data['paymentType'] = paymentType;
    data['noteForReturn'] = noteForReturn;
    data['created'] = created;
    data['category'] = category;

    data['isFavourite'] = isFavourite;
    data['productPrice'] = productPrice;
    data['programDiscountPercentage'] = programDiscountPercentage;
    data['programDiscountValue'] = programDiscountValue;
    data['priceAfterProgramInfluencer'] = priceAfterProgramInfluencer;
    data['influencerPercentage'] = influencerPercentage;
    data['influencerValue'] = influencerValue;
    data['priceWithInfluencer'] = priceWithInfluencer;
    data['maxDiscountWithFamous'] = maxDiscountWithFamous;
    data['productDiscountPercentage'] = productDiscountPercentage;
    data['productDiscountValue'] = productDiscountValue;
    data['priceBeforeDiscount'] = priceBeforeDiscount;
    data['maxProgramDiscountPercentage'] = maxProgramDiscountPercentage;
    data['finalDisplayPrice'] = finalDisplayPrice;
    data['offers'] = offers;
    data['discountPercentage'] = discountPercentage;
    return data;
  }
}

class OrderModelOrderProducts {
/*
{
  "id": "ea843e61-549a-4828-a3d5-08dc594228b7",
  "isDeleted": false,
  "productId": "b63ceb4e-8492-446c-54dd-08dc3db67684",
  "product": {
    "id": "b63ceb4e-8492-446c-54dd-08dc3db67684",
    "name": " أديداس أوريجينالز",
    "nameEn": "Adidas Originals",
    "description": " أديداس أوريجينالز",
    "descriptionEn": "Adidas Originals",
    "defaultPrice": 100,
    "oldPrice": 0,
    "orderNUmber": 0,
    "htmlDescriptions": "string",
    "htmlOther": "string",
    "isActive": true,
    "defaultPhotoId": "a0c4fb82-f403-4809-928d-0ae09428a04d",
    "defaultPhoto": {
      "id": "a0c4fb82-f403-4809-928d-0ae09428a04d",
      "imageId": "91f4c87d-6540-46fe-83f4-bc90ed624968",
      "name": "91f4c87d-6540-46fe-83f4-bc90ed624968.jpg",
      "fullLink": "https://sislimoda.com/Files/91f4c87d-6540-46fe-83f4-bc90ed624968.jpg"
    },
    "categoryId": "56e0235c-532b-409f-8784-08dc1e165a43",
    "vendorId": "0fd4806d-e6e6-48df-7b91-08dc1ed95a1b",
    "amount": 50,
    "brandId": "ff6982b0-f2e8-47c6-0ed6-08dc1e1a7720",
    "brand": null,
    "paymentType": "string",
    "noteForReturn": "string",
    "created": "06-03-2024 18:32:50",
    "category": null,
    "productImages": [
      null
    ],
    "productOptions": [
      null
    ],
    "productDetails": [
      null
    ],
    "isFavourite": false,
    "productPrice": 0,
    "programDiscountPercentage": 0,
    "programDiscountValue": 0,
    "priceAfterProgramInfluencer": 0,
    "influencerPercentage": 0,
    "influencerValue": 0,
    "priceWithInfluencer": 0,
    "maxDiscountWithFamous": 0,
    "productDiscountPercentage": 0,
    "productDiscountValue": 0,
    "priceBeforeDiscount": 0,
    "maxProgramDiscountPercentage": 0,
    "finalDisplayPrice": 0,
    "offers": null,
    "discountPercentage": 0
  },
  "ordersId": "0638b75f-9032-4609-8952-08dc5ba9082a",
  "amount": 1,
  "productPrice": 100,
  "totalWithAmount": 100,
  "userId": "1da8eac9-006a-4841-9fcd-bba67b258067",
  "user": {
    "id": "1da8eac9-006a-4841-9fcd-bba67b258067",
    "firstName": "ahmed",
    "middleName": "",
    "lastName": "almaz",
    "isActive": true,
    "address": "",
    "otherPhoneNumber": "",
    "isVendor": false,
    "isAdmin": false,
    "email": "a.almaz826@gmail.com",
    "userName": "a.almaz826@gmail.com",
    "phoneNumer": "99585048",
    "password": null,
    "photoId": null,
    "photo": null,
    "gender": 0,
    "birthDate": "1/1/0001 12:00:00 AM",
    "enableNotification": true,
    "pantsMeasurement": "",
    "coachMeasurement": "",
    "tShirtmeasurement": "XS",
    "isInfluencer": false,
    "socialLogin": 0,
    "isSocialLogin": false
  },
  "selectedProductOptions": [
    null
  ]
}
*/

  String? id;
  bool? isDeleted;
  String? productId;
  ProductModel? product;
  String? ordersId;
  String? amount;
  String? productPrice;
  String? totalWithAmount;
  String? userId;
  String? productPriceAfterSystemProfit;
  OrderModelOrderProductsUser? user;
  List<String?>? selectedProductOptions;

  OrderModelOrderProducts({
    this.id,
    this.isDeleted,
    this.productId,
    this.product,
    this.ordersId,
    this.amount,
    this.productPrice,
    this.totalWithAmount,
    this.userId,
    this.user,
    this.selectedProductOptions,
  });
  OrderModelOrderProducts.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    isDeleted = json['isDeleted'];
    productId = json['productId']?.toString();
    productPriceAfterSystemProfit =
        json['productPriceAfterSystemProfit']?.toString();
    product = (json['product'] != null)
        ? ProductModel.fromJson(json['product'])
        : null;
    ordersId = json['ordersId']?.toString();
    amount = json['amount']?.toString();
    productPrice = json['productPrice']?.toString();
    totalWithAmount = json['totalWithAmount']?.toString();
    userId = json['userId']?.toString();
    user = (json['user'] != null)
        ? OrderModelOrderProductsUser.fromJson(json['user'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['isDeleted'] = isDeleted;
    data['productId'] = productId;
    if (product != null) {
      data['product'] = product!.toJson();
    }
    data['ordersId'] = ordersId;
    data['amount'] = amount;
    data['productPrice'] = productPrice;
    data['totalWithAmount'] = totalWithAmount;
    data['userId'] = userId;
    if (user != null) {
      data['user'] = user!.toJson();
    }

    return data;
  }
}

class OrderModelUser {
/*
{
  "id": "1da8eac9-006a-4841-9fcd-bba67b258067",
  "firstName": "ahmed",
  "middleName": "",
  "lastName": "almaz",
  "isActive": true,
  "address": "",
  "otherPhoneNumber": "",
  "isVendor": false,
  "isAdmin": false,
  "email": "a.almaz826@gmail.com",
  "userName": "a.almaz826@gmail.com",
  "phoneNumer": "99585048",
  "password": null,
  "photoId": null,
  "photo": null,
  "gender": 0,
  "birthDate": "1/1/0001 12:00:00 AM",
  "enableNotification": true,
  "pantsMeasurement": "",
  "coachMeasurement": "",
  "tShirtmeasurement": "XS",
  "isInfluencer": false,
  "socialLogin": 0,
  "isSocialLogin": false
}
*/

  String? id;
  String? firstName;
  String? middleName;
  String? lastName;
  bool? isActive;
  String? address;
  String? otherPhoneNumber;
  bool? isVendor;
  bool? isAdmin;
  String? email;
  String? userName;
  String? phoneNumer;
  String? password;
  String? photoId;
  String? photo;
  String? gender;
  String? birthDate;
  bool? enableNotification;
  String? pantsMeasurement;
  String? coachMeasurement;
  String? tShirtmeasurement;
  bool? isInfluencer;
  String? socialLogin;
  bool? isSocialLogin;

  OrderModelUser({
    this.id,
    this.firstName,
    this.middleName,
    this.lastName,
    this.isActive,
    this.address,
    this.otherPhoneNumber,
    this.isVendor,
    this.isAdmin,
    this.email,
    this.userName,
    this.phoneNumer,
    this.password,
    this.photoId,
    this.photo,
    this.gender,
    this.birthDate,
    this.enableNotification,
    this.pantsMeasurement,
    this.coachMeasurement,
    this.tShirtmeasurement,
    this.isInfluencer,
    this.socialLogin,
    this.isSocialLogin,
  });
  OrderModelUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    firstName = json['firstName']?.toString();
    middleName = json['middleName']?.toString();
    lastName = json['lastName']?.toString();
    isActive = json['isActive'];
    address = json['address']?.toString();
    otherPhoneNumber = json['otherPhoneNumber']?.toString();
    isVendor = json['isVendor'];
    isAdmin = json['isAdmin'];
    email = json['email']?.toString();
    userName = json['userName']?.toString();
    phoneNumer = json['phoneNumer']?.toString();
    password = json['password']?.toString();
    photoId = json['photoId']?.toString();
    photo = json['photo']?.toString();
    gender = json['gender']?.toString();
    birthDate = json['birthDate']?.toString();
    enableNotification = json['enableNotification'];
    pantsMeasurement = json['pantsMeasurement']?.toString();
    coachMeasurement = json['coachMeasurement']?.toString();
    tShirtmeasurement = json['tShirtmeasurement']?.toString();
    isInfluencer = json['isInfluencer'];
    socialLogin = json['socialLogin']?.toString();
    isSocialLogin = json['isSocialLogin'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['firstName'] = firstName;
    data['middleName'] = middleName;
    data['lastName'] = lastName;
    data['isActive'] = isActive;
    data['address'] = address;
    data['otherPhoneNumber'] = otherPhoneNumber;
    data['isVendor'] = isVendor;
    data['isAdmin'] = isAdmin;
    data['email'] = email;
    data['userName'] = userName;
    data['phoneNumer'] = phoneNumer;
    data['password'] = password;
    data['photoId'] = photoId;
    data['photo'] = photo;
    data['gender'] = gender;
    data['birthDate'] = birthDate;
    data['enableNotification'] = enableNotification;
    data['pantsMeasurement'] = pantsMeasurement;
    data['coachMeasurement'] = coachMeasurement;
    data['tShirtmeasurement'] = tShirtmeasurement;
    data['isInfluencer'] = isInfluencer;
    data['socialLogin'] = socialLogin;
    data['isSocialLogin'] = isSocialLogin;
    return data;
  }
}

class OrderModelOrderStatus {
/*
{
  "id": "7d528ea5-f52d-4af9-f74f-08dc500b16b7",
  "value": 5,
  "nameAr": "test",
  "nameEn": "test",
  "optionSetId": "ff1829c3-facb-4220-37e8-08dc244c7b59",
  "optionSet": null,
  "color": "#6466f1",
  "isDefault": true
}
*/

  String? id;
  String? value;
  String? nameAr;
  String? nameEn;
  String? optionSetId;
  String? optionSet;
  String? color;
  bool? isDefault;

  OrderModelOrderStatus({
    this.id,
    this.value,
    this.nameAr,
    this.nameEn,
    this.optionSetId,
    this.optionSet,
    this.color,
    this.isDefault,
  });
  OrderModelOrderStatus.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    value = json['value']?.toString();
    nameAr = json['nameAr']?.toString();
    nameEn = json['nameEn']?.toString();
    optionSetId = json['optionSetId']?.toString();
    optionSet = json['optionSet']?.toString();
    color = json['color']?.toString();
    isDefault = json['isDefault'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['value'] = value;
    data['nameAr'] = nameAr;
    data['nameEn'] = nameEn;
    data['optionSetId'] = optionSetId;
    data['optionSet'] = optionSet;
    data['color'] = color;
    data['isDefault'] = isDefault;
    return data;
  }
}

class OrderModel {
  String? id;
  String? orderNumber;
  String? totalprice;
  String? totalDiscount;
  String? totalAfterDiscount;
  String? totalVat;
  String? totalAftetrVat;
  String? finalPrice;
  String? address;
  String? address2;
  String? lat;
  String? long;
  String? addressDetails;
  bool? isPaided;
  String? orderStatusId;
  OrderModelOrderStatus? orderStatus;
  String? country;
  String? city;
  String? district;
  String? userId;
  OrderModelUser? user;
  String? offersId;
  String? offers;
  String? couponId;
  String? coupon;
  String? couponCode;
  String? finalDisplayPrice;
  List<OrderModelOrderProducts?>? orderProducts;

  OrderModel({
    this.id,
    this.orderNumber,
    this.totalprice,
    this.totalDiscount,
    this.totalAfterDiscount,
    this.totalVat,
    this.totalAftetrVat,
    this.finalPrice,
    this.address,
    this.address2,
    this.lat,
    this.long,
    this.addressDetails,
    this.isPaided,
    this.orderStatusId,
    this.orderStatus,
    this.country,
    this.city,
    this.district,
    this.userId,
    this.user,
    this.offersId,
    this.offers,
    this.couponId,
    this.coupon,
    this.couponCode,
    this.orderProducts,
  });
  OrderModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    orderNumber = json['orderNumber']?.toString();
    totalprice = json['totalprice']?.toString();
    totalDiscount = json['totalDiscount']?.toString();
    totalAfterDiscount = json['totalAfterDiscount']?.toString();
    totalVat = json['totalVat']?.toString();
    totalAftetrVat = json['totalAftetrVat']?.toString();
    finalPrice = json['finalPrice']?.toString();
    address = json['address']?.toString();
    address2 = json['address2']?.toString();
    lat = json['lat']?.toString();
    long = json['long']?.toString();
    addressDetails = json['addressDetails']?.toString();
    isPaided = json['isPaided'];
    orderStatusId = json['orderStatusId']?.toString();
    orderStatus = (json['orderStatus'] != null)
        ? OrderModelOrderStatus.fromJson(json['orderStatus'])
        : null;
    country = json['country']?.toString();
    city = json['city']?.toString();
    district = json['district']?.toString();
    userId = json['userId']?.toString();
    user =
        (json['user'] != null) ? OrderModelUser.fromJson(json['user']) : null;
    offersId = json['offersId']?.toString();
    offers = json['offers']?.toString();
    couponId = json['couponId']?.toString();
    coupon = json['coupon']?.toString();
    couponCode = json['couponCode']?.toString();
    if (json['orderProducts'] != null) {
      final v = json['orderProducts'];
      final arr0 = <OrderModelOrderProducts>[];
      v.forEach((v) {
        arr0.add(OrderModelOrderProducts.fromJson(v));
      });
      orderProducts = arr0;
    }

    double tempFinalDisplayPrice = 0;
    double totalPromotion = 0;
    orderProducts!.forEach((element) {
      tempFinalDisplayPrice = tempFinalDisplayPrice +
          double.parse(element?.product?.valueToDisplayAfterDiscount ?? '0');
      // totalPromotion = totalPromotion +
      //     double.parse(element?.product?.offers?.code ?? '0');
    });
    finalDisplayPrice = district!.isNotEmpty
        ? district
        : tempFinalDisplayPrice.toStringAsFixed(2);
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['orderNumber'] = orderNumber;
    data['totalprice'] = totalprice;
    data['totalDiscount'] = totalDiscount;
    data['totalAfterDiscount'] = totalAfterDiscount;
    data['totalVat'] = totalVat;
    data['totalAftetrVat'] = totalAftetrVat;
    data['finalPrice'] = finalPrice;
    data['address'] = address;
    data['address2'] = address2;
    data['lat'] = lat;
    data['long'] = long;
    data['addressDetails'] = addressDetails;
    data['isPaided'] = isPaided;
    data['orderStatusId'] = orderStatusId;
    if (orderStatus != null) {
      data['orderStatus'] = orderStatus!.toJson();
    }
    data['country'] = country;
    data['city'] = city;
    data['district'] = district;
    data['userId'] = userId;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    data['offersId'] = offersId;
    data['offers'] = offers;
    data['couponId'] = couponId;
    data['coupon'] = coupon;
    data['couponCode'] = couponCode;
    if (orderProducts != null) {
      final v = orderProducts;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['orderProducts'] = arr0;
    }
    return data;
  }
}
