///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddOfferModelOffersProducts {
/*
{
  "offersId": "string",
  "productId": "string"
}
*/

  String? offersId;
  String? productId;

  AddOfferModelOffersProducts({
    this.offersId,
    this.productId,
  });
  AddOfferModelOffersProducts.fromJson(Map<String, dynamic> json) {
    offersId = json['offersId']?.toString();
    productId = json['productId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['offersId'] = offersId;
    data['productId'] = productId;
    return data;
  }
}

class AddOfferModel {
/*
{
  "code": "string",
  "title": "string",
  "description": "string",
  "titleEn": "string",
  "descriptionEn": "string",
  "offerType": 1,
  "amount": 0,
  "percent": 0,
  "mustExceed": 0,
  "startDate": "string",
  "endDate": "string",
  "photoId": "string",
  "isActive": true,
  "vendorId": "string",
  "isForVendor": true,
  "offerCategoryId": "string",
  "order": 0,
  "codeDescription": "string",
  "offersProducts": [
    {
      "offersId": "string",
      "productId": "string"
    }
  ]
}
*/

  String? code;
  String? title;
  String? description;
  String? titleEn;
  String? descriptionEn;
  String? offerType;
  String? amount;
  String? percent;
  String? mustExceed;
  String? startDate;
  String? endDate;
  String? photoId;
  bool? isActive;
  String? vendorId;
  bool? isForVendor;
  String? offerCategoryId;
  String? order;
  String? codeDescription;
  List<AddOfferModelOffersProducts?>? offersProducts;

  AddOfferModel({
    this.code,
    this.title,
    this.description,
    this.titleEn,
    this.descriptionEn,
    this.offerType,
    this.amount,
    this.percent,
    this.mustExceed,
    this.startDate,
    this.endDate,
    this.photoId,
    this.isActive,
    this.vendorId,
    this.isForVendor,
    this.offerCategoryId,
    this.order,
    this.codeDescription,
    this.offersProducts,
  });
  AddOfferModel.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toString();
    title = json['title']?.toString();
    description = json['description']?.toString();
    titleEn = json['titleEn']?.toString();
    descriptionEn = json['descriptionEn']?.toString();
    offerType = json['offerType']?.toString();
    amount = json['amount']?.toString();
    percent = json['percent']?.toString();
    mustExceed = json['mustExceed']?.toString();
    startDate = json['startDate']?.toString();
    endDate = json['endDate']?.toString();
    photoId = json['photoId']?.toString();
    isActive = json['isActive'];
    vendorId = json['vendorId']?.toString();
    isForVendor = json['isForVendor'];
    offerCategoryId = json['offerCategoryId']?.toString();
    order = json['order']?.toString();
    codeDescription = json['codeDescription']?.toString();
    if (json['offersProducts'] != null) {
      final v = json['offersProducts'];
      final arr0 = <AddOfferModelOffersProducts>[];
      v.forEach((v) {
        arr0.add(AddOfferModelOffersProducts.fromJson(v));
      });
      offersProducts = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['title'] = title;
    data['description'] = description;
    data['titleEn'] = titleEn;
    data['descriptionEn'] = descriptionEn;
    data['offerType'] = offerType;
    data['amount'] = amount;
    data['percent'] = percent;
    data['mustExceed'] = mustExceed;
    data['startDate'] = startDate;
    data['endDate'] = endDate;
    data['photoId'] = photoId;
    data['isActive'] = isActive;
    data['vendorId'] = vendorId;
    data['isForVendor'] = isForVendor;
    data['offerCategoryId'] = offerCategoryId;
    data['order'] = order;
    data['codeDescription'] = codeDescription;
    if (offersProducts != null) {
      final v = offersProducts;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['offersProducts'] = arr0;
    }
    return data;
  }
}
