///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AddTicketReplyModel {
/*
{
  "message": "test",
  "isDeleted": false,
  "ticketId": "65f8f7d3-9a56-4567-20fc-08dd695f6c76",
  "appUserId": "3b79445d-9ad3-421b-8af7-9a1c84a26bc7",
  "isInternal": false
}
*/

  String? message;
  bool? isDeleted;
  String? ticketId;
  String? appUserId;
  bool? isInternal;

  AddTicketReplyModel({
    this.message,
    this.isDeleted,
    this.ticketId,
    this.appUserId,
    this.isInternal,
  });
  AddTicketReplyModel.fromJson(Map<String, dynamic> json) {
    message = json['message']?.toString();
    isDeleted = json['isDeleted'];
    ticketId = json['ticketId']?.toString();
    appUserId = json['appUserId']?.toString();
    isInternal = json['isInternal'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['message'] = message;
    data['isDeleted'] = isDeleted;
    data['ticketId'] = ticketId;
    data['appUserId'] = appUserId;
    data['isInternal'] = isInternal;
    return data;
  }
}
