///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateInfluencerModelInfluencer {
/*
{
  "name": "string",
  "isActive": true,
  "photoId": "string",
  "userId": "string",
  "influencerStatusId": "string"
}
*/

  String? name;
  bool? isActive;
  String? photoId;
  String? userId;
  String? influencerStatusId;
  int? numberOfProduct;
  CreateInfluencerModelInfluencer({
    this.name,
    this.isActive,
    this.photoId,
    this.userId,
    this.influencerStatusId,
        this.numberOfProduct, 

  });
  CreateInfluencerModelInfluencer.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    isActive = json['isActive'];
    photoId = json['photoId']?.toString();
    userId = json['userId']?.toString();
    influencerStatusId = json['influencerStatusId']?.toString();
    numberOfProduct = json['numberOfProduct'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['isActive'] = isActive;
    data['photoId'] = photoId;
    data['userId'] = userId;
    data['influencerStatusId'] = influencerStatusId;
    data['numberOfProduct'] = numberOfProduct; 

    return data;
  }
}

class CreateInfluencerModelAppUser {
/*
{
  "firstName": "string",
  "middleName": "string",
  "lastName": "string",
  "isActive": true,
  "address": "string",
  "otherPhoneNumber": "string",
  "isVendor": true,
  "isAdmin": true,
  "email": "string",
  "userName": "string",
  "phoneNumer": "string",
  "password": "string",
  "photoId": "string",
  "gender": 0,
  "birthDate": "string",
  "enableNotification": true,
  "pantsMeasurement": "string",
  "coachMeasurement": "string",
  "tShirtmeasurement": "string",
  "isInfluencer": true,
  "socialLogin": 0,
  "isSocialLogin": true
}
*/

  String? firstName;
  String? middleName;
  String? lastName;
  bool? isActive;
  String? address;
  String? otherPhoneNumber;
  bool? isVendor;
  bool? isAdmin;
  String? email;
  String? userName;
  String? phoneNumer;
  String? password;
  String? photoId;
  String? gender;
  String? birthDate;
  bool? enableNotification;
  String? pantsMeasurement;
  String? coachMeasurement;
  String? tShirtmeasurement;
  bool? isInfluencer;
  String? socialLogin;
  bool? isSocialLogin;

  CreateInfluencerModelAppUser({
    this.firstName,
    this.middleName,
    this.lastName,
    this.isActive,
    this.address,
    this.otherPhoneNumber,
    this.isVendor,
    this.isAdmin,
    this.email,
    this.userName,
    this.phoneNumer,
    this.password,
    this.photoId,
    this.gender,
    this.birthDate,
    this.enableNotification,
    this.pantsMeasurement,
    this.coachMeasurement,
    this.tShirtmeasurement,
    this.isInfluencer,
    this.socialLogin,
    this.isSocialLogin,
  });
  CreateInfluencerModelAppUser.fromJson(Map<String, dynamic> json) {
    firstName = json['firstName']?.toString();
    middleName = json['middleName']?.toString();
    lastName = json['lastName']?.toString();
    isActive = json['isActive'];
    address = json['address']?.toString();
    otherPhoneNumber = json['otherPhoneNumber']?.toString();
    isVendor = json['isVendor'];
    isAdmin = json['isAdmin'];
    email = json['email']?.toString();
    userName = json['userName']?.toString();
    phoneNumer = json['phoneNumer']?.toString();
    password = json['password']?.toString();
    photoId = json['photoId']?.toString();
    gender = json['gender']?.toString();
    birthDate = json['birthDate']?.toString();
    enableNotification = json['enableNotification'];
    pantsMeasurement = json['pantsMeasurement']?.toString();
    coachMeasurement = json['coachMeasurement']?.toString();
    tShirtmeasurement = json['tShirtmeasurement']?.toString();
    isInfluencer = json['isInfluencer'];
    socialLogin = json['socialLogin']?.toString();
    isSocialLogin = json['isSocialLogin'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['firstName'] = firstName;
    data['middleName'] = middleName;
    data['lastName'] = lastName;
    data['isActive'] = isActive;
    data['address'] = address;
    data['otherPhoneNumber'] = otherPhoneNumber;
    data['isVendor'] = isVendor;
    data['isAdmin'] = isAdmin;
    data['email'] = email;
    data['userName'] = userName;
    data['phoneNumer'] = phoneNumer;
    data['password'] = password;
    data['photoId'] = photoId;
    data['gender'] = gender;
    data['birthDate'] = birthDate;
    data['enableNotification'] = enableNotification;
    data['pantsMeasurement'] = pantsMeasurement;
    data['coachMeasurement'] = coachMeasurement;
    data['tShirtmeasurement'] = tShirtmeasurement;
    data['isInfluencer'] = isInfluencer;
    data['socialLogin'] = socialLogin;
    data['isSocialLogin'] = isSocialLogin;
    return data;
  }
}

class CreateInfluencerModel {
/*
{
  "appUser": {
    "firstName": "string",
    "middleName": "string",
    "lastName": "string",
    "isActive": true,
    "address": "string",
    "otherPhoneNumber": "string",
    "isVendor": true,
    "isAdmin": true,
    "email": "string",
    "userName": "string",
    "phoneNumer": "string",
    "password": "string",
    "photoId": "string",
    "gender": 0,
    "birthDate": "string",
    "enableNotification": true,
    "pantsMeasurement": "string",
    "coachMeasurement": "string",
    "tShirtmeasurement": "string",
    "isInfluencer": true,
    "socialLogin": 0,
    "isSocialLogin": true
  },
  "influencer": {
    "name": "string",
    "isActive": true,
    "photoId": "string",
    "userId": "string",
    "influencerStatusId": "string"
  }
}
*/

  CreateInfluencerModelAppUser? appUser;
  CreateInfluencerModelInfluencer? influencer;

  CreateInfluencerModel({
    this.appUser,
    this.influencer,
  });
  CreateInfluencerModel.fromJson(Map<String, dynamic> json) {
    appUser = (json['appUser'] != null) ? CreateInfluencerModelAppUser.fromJson(json['appUser']) : null;
    influencer = (json['influencer'] != null) ? CreateInfluencerModelInfluencer.fromJson(json['influencer']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (appUser != null) {
      data['appUser'] = appUser!.toJson();
    }
    if (influencer != null) {
      data['influencer'] = influencer!.toJson();
    }
    return data;
  }
}
