///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CreateUserModelAppUser {
/*
{
  "firstName": "Ahmed",
  "middleName": "Abdelazeez",
  "lastName": "Almaz",
  "userName": "a.almaz12@gmail.com",
  "address": "Gesr Elsuez",
  "phoneNumber": "01555438040",
  "email": "a.almaz12@gmail.com",
  "password": "123456",
  "photoId": "ff9c797a-64d3-4e8c-ac97-7f958e7a97fd"
}
*/

  String? firstName;
  String? middleName;
  String? lastName;
  String? userName;
  String? address;
  String? phoneNumber;
  String? email;
  String? password;
  String? photoId;

  CreateUserModelAppUser({
    this.firstName,
    this.middleName,
    this.lastName,
    this.userName,
    this.address,
    this.phoneNumber,
    this.email,
    this.password,
    this.photoId,
  });
  CreateUserModelAppUser.fromJson(Map<String, dynamic> json) {
    firstName = json['firstName']?.toString();
    middleName = json['middleName']?.toString();
    lastName = json['lastName']?.toString();
    userName = json['userName']?.toString();
    address = json['address']?.toString();
    phoneNumber = json['phoneNumber']?.toString();
    email = json['email']?.toString();
    password = json['password']?.toString();
    photoId = json['photoId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['firstName'] = firstName;
    data['middleName'] = middleName;
    data['lastName'] = lastName;
    data['userName'] = userName;
    data['address'] = address;
    data['phoneNumber'] = phoneNumber;
    data['email'] = email;
    data['password'] = password;
    data['photoId'] = photoId;
    return data;
  }
}

class CreateUserModelUser {
/*
{
  "userTypes": 1,
  "isSupperAdmin": true,
  "name": "a.almaz12@gmail.com",
  "phoneNumber": "01555438040",
  "email": "a.almaz12@gmail.com",
  "photoId": "ff9c797a-64d3-4e8c-ac97-7f958e7a97fd"
}
*/

  String? userTypes;
  bool? isSupperAdmin;
  String? name;
  String? phoneNumber;
  String? email;
  String? photoId;

  CreateUserModelUser({
    this.userTypes,
    this.isSupperAdmin,
    this.name,
    this.phoneNumber,
    this.email,
    this.photoId,
  });
  CreateUserModelUser.fromJson(Map<String, dynamic> json) {
    userTypes = json['userTypes']?.toString();
    isSupperAdmin = json['isSupperAdmin'];
    name = json['name']?.toString();
    phoneNumber = json['phoneNumber']?.toString();
    email = json['email']?.toString();
    photoId = json['photoId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['userTypes'] = userTypes;
    data['isSupperAdmin'] = isSupperAdmin;
    data['name'] = name;
    data['phoneNumber'] = phoneNumber;
    data['email'] = email;
    data['photoId'] = photoId;
    return data;
  }
}

class CreateUserModel {
/*
{
  "user": {
    "userTypes": 1,
    "isSupperAdmin": true,
    "name": "a.almaz12@gmail.com",
    "phoneNumber": "01555438040",
    "email": "a.almaz12@gmail.com",
    "photoId": "ff9c797a-64d3-4e8c-ac97-7f958e7a97fd"
  },
  "appUser": {
    "firstName": "Ahmed",
    "middleName": "Abdelazeez",
    "lastName": "Almaz",
    "userName": "a.almaz12@gmail.com",
    "address": "Gesr Elsuez",
    "phoneNumber": "01555438040",
    "email": "a.almaz12@gmail.com",
    "password": "123456",
    "photoId": "ff9c797a-64d3-4e8c-ac97-7f958e7a97fd"
  }
}
*/

  CreateUserModelUser? user;
  CreateUserModelAppUser? appUser;

  CreateUserModel({
    this.user,
    this.appUser,
  });
  CreateUserModel.fromJson(Map<String, dynamic> json) {
    user = (json['user'] != null) ? CreateUserModelUser.fromJson(json['user']) : null;
    appUser = (json['appUser'] != null) ? CreateUserModelAppUser.fromJson(json['appUser']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (user != null) {
      data['user'] = user!.toJson();
    }
    if (appUser != null) {
      data['appUser'] = appUser!.toJson();
    }
    return data;
  }
}
