import 'dart:convert';

List<InfluencerModel> influencerModelFromJson(String str) =>
    List<InfluencerModel>.from(
        json.decode(str).map((x) => InfluencerModel.fromJson(x)));

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class InfluencerModelInfluencerStatus {
/*
{
  "id": "097aa6d0-32ea-4684-181d-08dc50589aad",
  "value": 2,
  "nameAr": "مقبول",
  "nameEn": "r",
  "optionSetId": "d607a5cb-5f9a-45eb-e7b6-08dc4fa2b1f5",
  "optionSet": null,
  "color": "#64f195",
  "isDefault": false
}
*/

  String? id;
  String? value;
  String? nameAr;
  String? nameEn;
  String? optionSetId;
  String? optionSet;
  String? color;
  bool? isDefault;

  InfluencerModelInfluencerStatus({
    this.id,
    this.value,
    this.nameAr,
    this.nameEn,
    this.optionSetId,
    this.optionSet,
    this.color,
    this.isDefault,
  });
  InfluencerModelInfluencerStatus.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    value = json['value']?.toString();
    nameAr = json['nameAr']?.toString();
    nameEn = json['nameEn']?.toString();
    optionSetId = json['optionSetId']?.toString();
    optionSet = json['optionSet']?.toString();
    color = json['color']?.toString();
    isDefault = json['isDefault'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['value'] = value;
    data['nameAr'] = nameAr;
    data['nameEn'] = nameEn;
    data['optionSetId'] = optionSetId;
    data['optionSet'] = optionSet;
    data['color'] = color;
    data['isDefault'] = isDefault;
    return data;
  }
}

class InfluencerModelUser {
/*
{
  "id": "dba085c5-9f20-41cd-8c90-8e60d881bb14",
  "firstName": "ahmed",
  "middleName": "abdelazeez",
  "lastName": "almaz",
  "isActive": true,
  "address": "test",
  "otherPhoneNumber": "01014927191",
  "isVendor": false,
  "isAdmin": false,
  "email": "a.almaz1000@gmail.com",
  "userName": "a.almaz1000@gmail.com",
  "phoneNumer": "01014927191",
  "password": null,
  "photoId": "3b37b60c-f234-43d5-8c0d-c12f961a23c3",
  "photo": null,
  "gender": 1,
  "birthDate": "1/21/2025 12:00:00 AM",
  "enableNotification": true,
  "pantsMeasurement": "",
  "coachMeasurement": "",
  "tShirtmeasurement": "",
  "isInfluencer": true,
  "socialLogin": 7,
  "isSocialLogin": true
}
*/

  String? id;
  String? firstName;
  String? middleName;
  String? lastName;
  bool? isActive;
  String? address;
  String? otherPhoneNumber;
  bool? isVendor;
  bool? isAdmin;
  String? email;
  String? userName;
  String? phoneNumer;
  String? password;
  String? photoId;
  String? photo;
  String? gender;
  String? birthDate;
  bool? enableNotification;
  String? pantsMeasurement;
  String? coachMeasurement;
  String? tShirtmeasurement;
  bool? isInfluencer;
  String? socialLogin;
  bool? isSocialLogin;

  InfluencerModelUser({
    this.id,
    this.firstName,
    this.middleName,
    this.lastName,
    this.isActive,
    this.address,
    this.otherPhoneNumber,
    this.isVendor,
    this.isAdmin,
    this.email,
    this.userName,
    this.phoneNumer,
    this.password,
    this.photoId,
    this.photo,
    this.gender,
    this.birthDate,
    this.enableNotification,
    this.pantsMeasurement,
    this.coachMeasurement,
    this.tShirtmeasurement,
    this.isInfluencer,
    this.socialLogin,
    this.isSocialLogin,
  });
  InfluencerModelUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    firstName = json['firstName']?.toString();
    middleName = json['middleName']?.toString();
    lastName = json['lastName']?.toString();
    isActive = json['isActive'];
    address = json['address']?.toString();
    otherPhoneNumber = json['otherPhoneNumber']?.toString();
    isVendor = json['isVendor'];
    isAdmin = json['isAdmin'];
    email = json['email']?.toString();
    userName = json['userName']?.toString();
    phoneNumer = json['phoneNumer']?.toString();
    password = json['password']?.toString();
    photoId = json['photoId']?.toString();
    photo = json['photo']?.toString();
    gender = json['gender']?.toString();
    birthDate = json['birthDate']?.toString();
    enableNotification = json['enableNotification'];
    pantsMeasurement = json['pantsMeasurement']?.toString();
    coachMeasurement = json['coachMeasurement']?.toString();
    tShirtmeasurement = json['tShirtmeasurement']?.toString();
    isInfluencer = json['isInfluencer'];
    socialLogin = json['socialLogin']?.toString();
    isSocialLogin = json['isSocialLogin'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['firstName'] = firstName;
    data['middleName'] = middleName;
    data['lastName'] = lastName;
    data['isActive'] = isActive;
    data['address'] = address;
    data['otherPhoneNumber'] = otherPhoneNumber;
    data['isVendor'] = isVendor;
    data['isAdmin'] = isAdmin;
    data['email'] = email;
    data['userName'] = userName;
    data['phoneNumer'] = phoneNumer;
    data['password'] = password;
    data['photoId'] = photoId;
    data['photo'] = photo;
    data['gender'] = gender;
    data['birthDate'] = birthDate;
    data['enableNotification'] = enableNotification;
    data['pantsMeasurement'] = pantsMeasurement;
    data['coachMeasurement'] = coachMeasurement;
    data['tShirtmeasurement'] = tShirtmeasurement;
    data['isInfluencer'] = isInfluencer;
    data['socialLogin'] = socialLogin;
    data['isSocialLogin'] = isSocialLogin;
    return data;
  }
}

class InfluencerModelPhoto {
/*
{
  "id": "3b37b60c-f234-43d5-8c0d-c12f961a23c3",
  "imageId": "a04bf69e-e5d9-49b0-8982-99eff1ea32af",
  "name": "a04bf69e-e5d9-49b0-8982-99eff1ea32af.png",
  "fullLink": "https://sislimoda.com/Files/a04bf69e-e5d9-49b0-8982-99eff1ea32af.png"
}
*/

  String? id;
  String? imageId;
  String? name;
  String? fullLink;

  InfluencerModelPhoto({
    this.id,
    this.imageId,
    this.name,
    this.fullLink,
  });
  InfluencerModelPhoto.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    imageId = json['imageId']?.toString();
    name = json['name']?.toString();
    fullLink = json['fullLink']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['imageId'] = imageId;
    data['name'] = name;
    data['fullLink'] = fullLink;
    return data;
  }
}

class InfluencerModel {
/*
{
  "id": "78556318-ee9a-4cb6-ff88-08dd3a3f9afd",
  "name": "ahmed almaz",
  "isActive": true,
  "photoId": "3b37b60c-f234-43d5-8c0d-c12f961a23c3",
  "photo": {
    "id": "3b37b60c-f234-43d5-8c0d-c12f961a23c3",
    "imageId": "a04bf69e-e5d9-49b0-8982-99eff1ea32af",
    "name": "a04bf69e-e5d9-49b0-8982-99eff1ea32af.png",
    "fullLink": "https://sislimoda.com/Files/a04bf69e-e5d9-49b0-8982-99eff1ea32af.png"
  },
  "userId": "dba085c5-9f20-41cd-8c90-8e60d881bb14",
  "user": {
    "id": "dba085c5-9f20-41cd-8c90-8e60d881bb14",
    "firstName": "ahmed",
    "middleName": "abdelazeez",
    "lastName": "almaz",
    "isActive": true,
    "address": "test",
    "otherPhoneNumber": "01014927191",
    "isVendor": false,
    "isAdmin": false,
    "email": "a.almaz1000@gmail.com",
    "userName": "a.almaz1000@gmail.com",
    "phoneNumer": "01014927191",
    "password": null,
    "photoId": "3b37b60c-f234-43d5-8c0d-c12f961a23c3",
    "photo": null,
    "gender": 1,
    "birthDate": "1/21/2025 12:00:00 AM",
    "enableNotification": true,
    "pantsMeasurement": "",
    "coachMeasurement": "",
    "tShirtmeasurement": "",
    "isInfluencer": true,
    "socialLogin": 7,
    "isSocialLogin": true
  },
  "influencerStatusId": "097aa6d0-32ea-4684-181d-08dc50589aad",
  "influencerStatus": {
    "id": "097aa6d0-32ea-4684-181d-08dc50589aad",
    "value": 2,
    "nameAr": "مقبول",
    "nameEn": "r",
    "optionSetId": "d607a5cb-5f9a-45eb-e7b6-08dc4fa2b1f5",
    "optionSet": null,
    "color": "#64f195",
    "isDefault": false
  },
  "numberOfProduct": 0,
  "idNumber": "1231231231213",
  "bankAccountNumber": "123123123",
  "whatsappNumber1": "01555438049",
  "whatsappNumber2": "01014927191",
  "telegramNumber1": "01014927191",
  "telegramNumber2": null,
  "facebookLink": null,
  "twitterLink": null,
  "instagramLink": "01014927191",
  "linkedInLink": null,
  "youTubeLink": null,
  "snapchatLink": null,
  "tikTokLink": null
}
*/

  String? id;
  String? name;
  bool? isActive;
  String? photoId;
  InfluencerModelPhoto? photo;
  String? userId;
  InfluencerModelUser? user;
  String? influencerStatusId;
  InfluencerModelInfluencerStatus? influencerStatus;
  String? numberOfProduct;
  String? idNumber;
  String? bankAccountNumber;
  String? whatsappNumber1;
  String? whatsappNumber2;
  String? telegramNumber1;
  String? telegramNumber2;
  String? facebookLink;
  String? twitterLink;
  String? instagramLink;
  String? linkedInLink;
  String? youTubeLink;
  String? snapchatLink;
  String? tikTokLink;

  InfluencerModel({
    this.id,
    this.name,
    this.isActive,
    this.photoId,
    this.photo,
    this.userId,
    this.user,
    this.influencerStatusId,
    this.influencerStatus,
    this.numberOfProduct,
    this.idNumber,
    this.bankAccountNumber,
    this.whatsappNumber1,
    this.whatsappNumber2,
    this.telegramNumber1,
    this.telegramNumber2,
    this.facebookLink,
    this.twitterLink,
    this.instagramLink,
    this.linkedInLink,
    this.youTubeLink,
    this.snapchatLink,
    this.tikTokLink,
  });
  InfluencerModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    isActive = json['isActive'];
    photoId = json['photoId']?.toString();
    photo = (json['photo'] != null)
        ? InfluencerModelPhoto.fromJson(json['photo'])
        : null;
    userId = json['userId']?.toString();
    user = (json['user'] != null)
        ? InfluencerModelUser.fromJson(json['user'])
        : null;
    influencerStatusId = json['influencerStatusId']?.toString();
    influencerStatus = (json['influencerStatus'] != null)
        ? InfluencerModelInfluencerStatus.fromJson(json['influencerStatus'])
        : null;
    numberOfProduct = json['numberOfProduct']?.toString();
    idNumber = json['idNumber']?.toString();
    bankAccountNumber = json['bankAccountNumber']?.toString();
    whatsappNumber1 = json['whatsappNumber1']?.toString();
    whatsappNumber2 = json['whatsappNumber2']?.toString();
    telegramNumber1 = json['telegramNumber1']?.toString();
    telegramNumber2 = json['telegramNumber2']?.toString();
    facebookLink = json['facebookLink']?.toString();
    twitterLink = json['twitterLink']?.toString();
    instagramLink = json['instagramLink']?.toString();
    linkedInLink = json['linkedInLink']?.toString();
    youTubeLink = json['youTubeLink']?.toString();
    snapchatLink = json['snapchatLink']?.toString();
    tikTokLink = json['tikTokLink']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id != "string" ? id : null;
    data['name'] = name;
    data['isActive'] = isActive;
data['photoId'] = photoId != "string" ? photoId : null;
    // if (photo != null) {
    //   data['photo'] = photo!.toJson();
    // }
data['userId'] = userId != "string" ? userId : null;
    if (user != null) {
      data['user'] = user!.toJson();
    }
data['influencerStatusId'] = influencerStatusId != "string" ? influencerStatusId : null;
    // if (influencerStatus != null) {
    //   data['influencerStatus'] = influencerStatus!.toJson();
    // }
    data['numberOfProduct'] = numberOfProduct;
    data['idNumber'] = idNumber;
    data['bankAccountNumber'] = bankAccountNumber;
    data['whatsappNumber1'] = whatsappNumber1;
    data['whatsappNumber2'] = whatsappNumber2;
    data['telegramNumber1'] = telegramNumber1;
    data['telegramNumber2'] = telegramNumber2;
    data['facebookLink'] = facebookLink;
    data['twitterLink'] = twitterLink;
    data['instagramLink'] = instagramLink;
    data['linkedInLink'] = linkedInLink;
    data['youTubeLink'] = youTubeLink;
    data['snapchatLink'] = snapchatLink;
    data['tikTokLink'] = tikTokLink;
    return data;
  }
}
