///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UpdateUserModel {
/*
{
  "id": "string",
  "name": "string",
  "phoneNumber": "string",
  "email": "string",
  "userTypes": 1,
  "photoId": "string",
  "appUserId": "string",
  "vendorId": "string",
  "isSupperAdmin": true
}
*/

  String? id;
  String? name;
  String? phoneNumber;
  String? email;
  String? userTypes;
  String? photoId;
  String? appUserId;
  String? vendorId;
  bool? isSupperAdmin;

  UpdateUserModel({
    this.id,
    this.name,
    this.phoneNumber,
    this.email,
    this.userTypes,
    this.photoId,
    this.appUserId,
    this.vendorId,
    this.isSupperAdmin,
  });
  UpdateUserModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    phoneNumber = json['phoneNumber']?.toString();
    email = json['email']?.toString();
    userTypes = json['userTypes']?.toString();
    photoId = json['photoId']?.toString();
    appUserId = json['appUserId']?.toString();
    vendorId = json['vendorId']?.toString();
    isSupperAdmin = json['isSupperAdmin'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['phoneNumber'] = phoneNumber;
    data['email'] = email;
    data['userTypes'] = userTypes;
    data['photoId'] = photoId;
    data['appUserId'] = appUserId;
    data['vendorId'] = vendorId;
    data['isSupperAdmin'] = isSupperAdmin;
    return data;
  }
}
