///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UpdateInfluencerModel {
/*
{
  "id": "string",
  "name": "string",
  "isActive": true,
  "photoId": "string",
  "userId": "string",
  "influencerStatusId": "string",
  "numberOfProduct": 0,
  "idNumber": "string",
  "bankAccountNumber": "string",
  "whatsappNumber1": "string",
  "whatsappNumber2": "string",
  "telegramNumber1": "string",
  "telegramNumber2": "string",
  "facebookLink": "string",
  "twitterLink": "string",
  "instagramLink": "string",
  "linkedInLink": "string",
  "youTubeLink": "string",
  "snapchatLink": "string",
  "tikTokLink": "string"
}
*/

  String? id;
  String? name;
  bool? isActive;
  String? photoId;
  String? userId;
  String? influencerStatusId;
  int? numberOfProduct;
  String? idNumber;
  String? bankAccountNumber;
  String? whatsappNumber1;
  String? whatsappNumber2;
  String? telegramNumber1;
  String? telegramNumber2;
  String? facebookLink;
  String? twitterLink;
  String? instagramLink;
  String? linkedInLink;
  String? youTubeLink;
  String? snapchatLink;
  String? tikTokLink;

  UpdateInfluencerModel({
    this.id,
    this.name,
    this.isActive,
    this.photoId,
    this.userId,
    this.influencerStatusId,
    this.numberOfProduct,
    this.idNumber,
    this.bankAccountNumber,
    this.whatsappNumber1,
    this.whatsappNumber2,
    this.telegramNumber1,
    this.telegramNumber2,
    this.facebookLink,
    this.twitterLink,
    this.instagramLink,
    this.linkedInLink,
    this.youTubeLink,
    this.snapchatLink,
    this.tikTokLink,
  });
  UpdateInfluencerModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    isActive = json['isActive'];
    photoId = json['photoId']?.toString();
    userId = json['userId']?.toString();
    influencerStatusId = json['influencerStatusId']?.toString();
      numberOfProduct=json['numberOfProduct'] is int
          ? json['numberOfProduct']
          : int.tryParse(json['numberOfProduct']?.toString() ?? '');
              idNumber = json['idNumber']?.toString();
    bankAccountNumber = json['bankAccountNumber']?.toString();
    whatsappNumber1 = json['whatsappNumber1']?.toString();
    whatsappNumber2 = json['whatsappNumber2']?.toString();
    telegramNumber1 = json['telegramNumber1']?.toString();
    telegramNumber2 = json['telegramNumber2']?.toString();
    facebookLink = json['facebookLink']?.toString();
    twitterLink = json['twitterLink']?.toString();
    instagramLink = json['instagramLink']?.toString();
    linkedInLink = json['linkedInLink']?.toString();
    youTubeLink = json['youTubeLink']?.toString();
    snapchatLink = json['snapchatLink']?.toString();
    tikTokLink = json['tikTokLink']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['isActive'] = isActive;
    data['photoId'] = photoId;
    data['userId'] = userId;
    data['influencerStatusId'] = influencerStatusId;
    data['numberOfProduct'] = numberOfProduct;
    data['idNumber'] = idNumber;
    data['bankAccountNumber'] = bankAccountNumber;
    data['whatsappNumber1'] = whatsappNumber1;
    data['whatsappNumber2'] = whatsappNumber2;
    data['telegramNumber1'] = telegramNumber1;
    data['telegramNumber2'] = telegramNumber2;
    data['facebookLink'] = facebookLink;
    data['twitterLink'] = twitterLink;
    data['instagramLink'] = instagramLink;
    data['linkedInLink'] = linkedInLink;
    data['youTubeLink'] = youTubeLink;
    data['snapchatLink'] = snapchatLink;
    data['tikTokLink'] = tikTokLink;
    return data;
  }
}
