///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UserModelPhoto {
/*
{
  "id": "240a2f89-2743-40a1-b8fa-443cb8caf8c9",
  "imageId": "2784c61b-3680-499b-8258-dc70dac906ba",
  "name": "2784c61b-3680-499b-8258-dc70dac906ba.png",
  "fullLink": "https://sislimoda.com/Files/2784c61b-3680-499b-8258-dc70dac906ba.png"
}
*/

  String? id;
  String? imageId;
  String? name;
  String? fullLink;

  UserModelPhoto({
    this.id,
    this.imageId,
    this.name,
    this.fullLink,
  });
  UserModelPhoto.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    imageId = json['imageId']?.toString();
    name = json['name']?.toString();
    fullLink = json['fullLink']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['imageId'] = imageId;
    data['name'] = name;
    data['fullLink'] = fullLink;
    return data;
  }
}

class UserModel {
/*
{
  "id": "16cb227b-43c6-491c-bcb9-c7c3024f2483",
  "firstName": "ahmed",
  "middleName": "ahmed ",
  "lastName": "almaz",
  "isActive": false,
  "address": "amr ebn elass",
  "otherPhoneNumber": "",
  "isVendor": true,
  "isAdmin": false,
  "email": "sislimodavendor@gmail.com",
  "userName": "sislimodavendor@gmail.com",
  "phoneNumer": null,
  "photoId": "240a2f89-2743-40a1-b8fa-443cb8caf8c9",
  "photo": {
    "id": "240a2f89-2743-40a1-b8fa-443cb8caf8c9",
    "imageId": "2784c61b-3680-499b-8258-dc70dac906ba",
    "name": "2784c61b-3680-499b-8258-dc70dac906ba.png",
    "fullLink": "https://sislimoda.com/Files/2784c61b-3680-499b-8258-dc70dac906ba.png"
  },
  "gender": 1,
  "birthDate": null,
  "photoUrl": null,
  "enableNotification": true,
  "pantsMeasurement": "",
  "coachMeasurement": "",
  "tShirtmeasurement": "",
  "isInfluencer": false,
  "socialLogin": 0,
  "isSocialLogin": false
}
*/

  String? id;
  String? firstName;
  String? middleName;
  String? lastName;
  bool? isActive;
  String? address;
  String? otherPhoneNumber;
  bool? isVendor;
  bool? isAdmin;
  String? email;
  String? userName;
  String? phoneNumer;
  String? photoId;
  UserModelPhoto? photo;
  String? gender;
  String? birthDate;
  String? photoUrl;
  bool? enableNotification;
  String? pantsMeasurement;
  String? coachMeasurement;
  String? tShirtmeasurement;
  bool? isInfluencer;
  String? socialLogin;
  bool? isSocialLogin;

  UserModel({
    this.id,
    this.firstName,
    this.middleName,
    this.lastName,
    this.isActive,
    this.address,
    this.otherPhoneNumber,
    this.isVendor,
    this.isAdmin,
    this.email,
    this.userName,
    this.phoneNumer,
    this.photoId,
    this.photo,
    this.gender,
    this.birthDate,
    this.photoUrl,
    this.enableNotification,
    this.pantsMeasurement,
    this.coachMeasurement,
    this.tShirtmeasurement,
    this.isInfluencer,
    this.socialLogin,
    this.isSocialLogin,
  });
  UserModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    firstName = json['firstName']?.toString();
    middleName = json['middleName']?.toString();
    lastName = json['lastName']?.toString();
    isActive = json['isActive'];
    address = json['address']?.toString();
    otherPhoneNumber = json['otherPhoneNumber']?.toString();
    isVendor = json['isVendor'];
    isAdmin = json['isAdmin'];
    email = json['email']?.toString();
    userName = json['userName']?.toString();
    phoneNumer = json['phoneNumer']?.toString();
    photoId = json['photoId']?.toString();
    photo =
        (json['photo'] != null) ? UserModelPhoto.fromJson(json['photo']) : null;
    gender = json['gender']?.toString();
    birthDate = json['birthDate']?.toString();
    photoUrl = json['photoUrl']?.toString();
    enableNotification = json['enableNotification'];
    pantsMeasurement = json['pantsMeasurement']?.toString();
    coachMeasurement = json['coachMeasurement']?.toString();
    tShirtmeasurement = json['tShirtmeasurement']?.toString();
    isInfluencer = json['isInfluencer'];
    socialLogin = json['socialLogin']?.toString();
    isSocialLogin = json['isSocialLogin'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['firstName'] = firstName;
    data['middleName'] = middleName;
    data['lastName'] = lastName;
    data['isActive'] = isActive;
    data['address'] = address;
    data['otherPhoneNumber'] = otherPhoneNumber;
    data['isVendor'] = isVendor;
    data['isAdmin'] = isAdmin;
    data['email'] = email;
    data['userName'] = userName;
    data['phoneNumer'] = phoneNumer;
    data['photoId'] = photoId;
    if (photo != null) {
      data['photo'] = photo!.toJson();
    }
    data['gender'] = gender;
    data['birthDate'] = birthDate;
    data['photoUrl'] = photoUrl;
    data['enableNotification'] = enableNotification;
    data['pantsMeasurement'] = pantsMeasurement;
    data['coachMeasurement'] = coachMeasurement;
    data['tShirtmeasurement'] = tShirtmeasurement;
    data['isInfluencer'] = isInfluencer;
    data['socialLogin'] = socialLogin;
    data['isSocialLogin'] = isSocialLogin;
    return data;
  }
}
