///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ConvertToDummyOrderModel {
/*
{
  "quantity": 5,
  "productId": "65caad3064b0b79f94522dc7"
}
*/

  String? quantity;
  String? name;
  String? productId;

  ConvertToDummyOrderModel({this.quantity, this.productId, this.name});
  ConvertToDummyOrderModel.fromJson(Map<String, dynamic> json) {
    quantity = json['quantity']?.toString();
    productId = json['productId']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['quantity'] = quantity;
    data['productId'] = productId;
    return data;
  }
}
