import 'dart:convert';

List<CountryModel> countryModelFromJson(String str) => List<CountryModel>.from(
    json.decode(str).map((x) => CountryModel.fromJson(x)));

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CountryModelPhoto {
/*
{
  "id": "0cf8e8ae-6bfd-41bb-b075-4ac93d70d377",
  "imageId": "35be9657-d8f3-4be1-8cc7-448719689302",
  "name": "35be9657-d8f3-4be1-8cc7-448719689302.png",
  "fullLink": "https://sislimoda.com/Files/35be9657-d8f3-4be1-8cc7-448719689302.png"
}
*/

  String? id;
  String? imageId;
  String? name;
  String? fullLink;

  CountryModelPhoto({
    this.id,
    this.imageId,
    this.name,
    this.fullLink,
  });
  CountryModelPhoto.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    imageId = json['imageId']?.toString();
    name = json['name']?.toString();
    fullLink = json['fullLink']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['imageId'] = imageId;
    data['name'] = name;
    data['fullLink'] = fullLink;
    return data;
  }
}

class CountryModel {
/*
{
  "id": "c62c0e4a-8297-4387-2aca-08dc1d4d17f9",
  "countryId": 0,
  "name": "مصر",
  "nameEn": "egypt",
  "code": "+20",
  "isoCode": "eg",
  "isActive": true,
  "photoId": "0cf8e8ae-6bfd-41bb-b075-4ac93d70d377",
  "photo": {
    "id": "0cf8e8ae-6bfd-41bb-b075-4ac93d70d377",
    "imageId": "35be9657-d8f3-4be1-8cc7-448719689302",
    "name": "35be9657-d8f3-4be1-8cc7-448719689302.png",
    "fullLink": "https://sislimoda.com/Files/35be9657-d8f3-4be1-8cc7-448719689302.png"
  }
}
*/

  String? id;
  String? countryId;
  String? name;
  String? nameEn;
  String? code;
  String? isoCode;
  bool? isActive;
  String? photoId;
  CountryModelPhoto? photo;

  CountryModel({
    this.id,
    this.countryId,
    this.name,
    this.nameEn,
    this.code,
    this.isoCode,
    this.isActive,
    this.photoId,
    this.photo,
  });
  CountryModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    countryId = json['countryId']?.toString();
    name = json['name']?.toString();
    nameEn = json['nameEn']?.toString();
    code = json['code']?.toString();
    isoCode = json['isoCode']?.toString();
    isActive = json['isActive'];
    photoId = json['photoId']?.toString();
    photo = (json['photo'] != null)
        ? CountryModelPhoto.fromJson(json['photo'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['countryId'] = countryId;
    data['name'] = name;
    data['nameEn'] = nameEn;
    data['code'] = code;
    data['isoCode'] = isoCode;
    data['isActive'] = isActive;
    data['photoId'] = photoId;
    if (photo != null) {
      data['photo'] = photo!.toJson();
    }
    return data;
  }
}
