import 'dart:convert';

List<ProductOptionModel> productOptionModelFromJson(String str) =>
    List<ProductOptionModel>.from(
        json.decode(str).map((x) => ProductOptionModel.fromJson(x)));

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProductOptionModel {
/*
{
  "id": "dccb6563-020b-48df-7afb-08dc1e1b5cbd",
  "name": "اسود",
  "nameEn": "Black",
  "optionType": 1,
  "other": "#212121",
  "categoryId": null,
  "category": null,
  "groupName": null,
  "groupKey": null
}
*/

  String? id;
  String? name;
  String? nameEn;
  String? optionType;
  String? other;
  String? categoryId;
  String? category;
  String? groupName;
  String? groupKey;

  ProductOptionModel({
    this.id,
    this.name,
    this.nameEn,
    this.optionType,
    this.other,
    this.categoryId,
    this.category,
    this.groupName,
    this.groupKey,
  });
  ProductOptionModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    nameEn = json['nameEn']?.toString();
    optionType = json['optionType']?.toString();
    other = json['other']?.toString();
    categoryId = json['categoryId']?.toString();
    category = json['category']?.toString();
    groupName = json['groupName']?.toString();
    groupKey = json['groupKey']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['nameEn'] = nameEn;
    data['optionType'] = optionType;
    data['other'] = other;
    data['categoryId'] = categoryId;
    data['category'] = category;
    data['groupName'] = groupName;
    data['groupKey'] = groupKey;
    return data;
  }
}
