import 'dart:convert';

List<Review> reviewModelFromJson(String str) =>
    List<Review>.from(json.decode(str).map((x) => Review.fromJson(x)));

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ReviewProductEvaluationImagesPhoto {
/*
{
  "id": "f7a82235-cdae-436b-9c2f-f48e7c36497c",
  "imageId": "82d961d3-35da-4afc-abb0-184544e26051",
  "name": "82d961d3-35da-4afc-abb0-184544e26051.jpg",
  "fullLink": "https://sislimoda.com/Files/82d961d3-35da-4afc-abb0-184544e26051.jpg"
}
*/

  String? id;
  String? imageId;
  String? name;
  String? fullLink;

  ReviewProductEvaluationImagesPhoto({
    this.id,
    this.imageId,
    this.name,
    this.fullLink,
  });
  ReviewProductEvaluationImagesPhoto.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    imageId = json['imageId']?.toString();
    name = json['name']?.toString();
    fullLink = json['fullLink']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['imageId'] = imageId;
    data['name'] = name;
    data['fullLink'] = fullLink;
    return data;
  }
}

class ReviewProductEvaluationImages {
/*
{
  "photoId": "f7a82235-cdae-436b-9c2f-f48e7c36497c",
  "photo": {
    "id": "f7a82235-cdae-436b-9c2f-f48e7c36497c",
    "imageId": "82d961d3-35da-4afc-abb0-184544e26051",
    "name": "82d961d3-35da-4afc-abb0-184544e26051.jpg",
    "fullLink": "https://sislimoda.com/Files/82d961d3-35da-4afc-abb0-184544e26051.jpg"
  }
}
*/

  String? photoId;
  ReviewProductEvaluationImagesPhoto? photo;

  ReviewProductEvaluationImages({
    this.photoId,
    this.photo,
  });
  ReviewProductEvaluationImages.fromJson(Map<String, dynamic> json) {
    photoId = json['photoId']?.toString();
    photo = (json['photo'] != null)
        ? ReviewProductEvaluationImagesPhoto.fromJson(json['photo'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['photoId'] = photoId;
    if (photo != null) {
      data['photo'] = photo!.toJson();
    }
    return data;
  }
}

class ReviewEvaluationApproveStatus {
/*
{
  "id": "f445c400-4fa9-49f7-2bb4-08dd6b51bdb1",
  "value": 1,
  "nameAr": "جديد",
  "nameEn": "New",
  "optionSetId": "782a47be-2da4-4dab-ccfb-08dd66253331",
  "optionSet": null,
  "color": "#EF5350",
  "isDefault": false
}
*/

  String? id;
  String? value;
  String? nameAr;
  String? nameEn;
  String? optionSetId;
  String? optionSet;
  String? color;
  bool? isDefault;

  ReviewEvaluationApproveStatus({
    this.id,
    this.value,
    this.nameAr,
    this.nameEn,
    this.optionSetId,
    this.optionSet,
    this.color,
    this.isDefault,
  });
  ReviewEvaluationApproveStatus.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    value = json['value']?.toString();
    nameAr = json['nameAr']?.toString();
    nameEn = json['nameEn']?.toString();
    optionSetId = json['optionSetId']?.toString();
    optionSet = json['optionSet']?.toString();
    color = json['color']?.toString();
    isDefault = json['isDefault'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['value'] = value;
    data['nameAr'] = nameAr;
    data['nameEn'] = nameEn;
    data['optionSetId'] = optionSetId;
    data['optionSet'] = optionSet;
    data['color'] = color;
    data['isDefault'] = isDefault;
    return data;
  }
}

class ReviewImage {
/*
{
  "id": "f7a82235-cdae-436b-9c2f-f48e7c36497c",
  "imageId": "82d961d3-35da-4afc-abb0-184544e26051",
  "name": "82d961d3-35da-4afc-abb0-184544e26051.jpg",
  "fullLink": "https://sislimoda.com/Files/82d961d3-35da-4afc-abb0-184544e26051.jpg"
}
*/

  String? id;
  String? imageId;
  String? name;
  String? fullLink;

  ReviewImage({
    this.id,
    this.imageId,
    this.name,
    this.fullLink,
  });
  ReviewImage.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    imageId = json['imageId']?.toString();
    name = json['name']?.toString();
    fullLink = json['fullLink']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['imageId'] = imageId;
    data['name'] = name;
    data['fullLink'] = fullLink;
    return data;
  }
}

class Review {
/*
{
  "id": "4528740a-a5fa-489b-538d-08dd6606c184",
  "description": "test",
  "productId": "f41839c1-da57-4ccc-e294-08dc1ee594c7",
  "product": null,
  "rate": 5,
  "userFullName": "Abdelmonem Helmy",
  "created": "18-03-2025 11:22:15",
  "createdDateTime": "03 Tuesday 2025",
  "createdSinceTime": "6 days ago",
  "imageId": "f7a82235-cdae-436b-9c2f-f48e7c36497c",
  "image": {
    "id": "f7a82235-cdae-436b-9c2f-f48e7c36497c",
    "imageId": "82d961d3-35da-4afc-abb0-184544e26051",
    "name": "82d961d3-35da-4afc-abb0-184544e26051.jpg",
    "fullLink": "https://sislimoda.com/Files/82d961d3-35da-4afc-abb0-184544e26051.jpg"
  },
  "evaluationApproveStatusId": "f445c400-4fa9-49f7-2bb4-08dd6b51bdb1",
  "evaluationApproveStatus": {
    "id": "f445c400-4fa9-49f7-2bb4-08dd6b51bdb1",
    "value": 1,
    "nameAr": "جديد",
    "nameEn": "New",
    "optionSetId": "782a47be-2da4-4dab-ccfb-08dd66253331",
    "optionSet": null,
    "color": "#EF5350",
    "isDefault": false
  },
  "productEvaluationImages": [
    {
      "photoId": "f7a82235-cdae-436b-9c2f-f48e7c36497c",
      "photo": {
        "id": "f7a82235-cdae-436b-9c2f-f48e7c36497c",
        "imageId": "82d961d3-35da-4afc-abb0-184544e26051",
        "name": "82d961d3-35da-4afc-abb0-184544e26051.jpg",
        "fullLink": "https://sislimoda.com/Files/82d961d3-35da-4afc-abb0-184544e26051.jpg"
      }
    }
  ]
}
*/

  String? id;
  String? description;
  String? productId;
  String? product;
  String? rate;
  String? userFullName;
  String? created;
  String? createdDateTime;
  String? createdSinceTime;
  String? imageId;
  ReviewImage? image;
  String? evaluationApproveStatusId;
  ReviewEvaluationApproveStatus? evaluationApproveStatus;
  List<ReviewProductEvaluationImages?>? productEvaluationImages;

  Review({
    this.id,
    this.description,
    this.productId,
    this.product,
    this.rate,
    this.userFullName,
    this.created,
    this.createdDateTime,
    this.createdSinceTime,
    this.imageId,
    this.image,
    this.evaluationApproveStatusId,
    this.evaluationApproveStatus,
    this.productEvaluationImages,
  });
  Review.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    description = json['description']?.toString();
    productId = json['productId']?.toString();
    product = json['product']?.toString();
    rate = json['rate']?.toString();
    userFullName = json['userFullName']?.toString();
    created = json['created']?.toString();
    createdDateTime = json['createdDateTime']?.toString();
    createdSinceTime = json['createdSinceTime']?.toString();
    imageId = json['imageId']?.toString();
    image =
        (json['image'] != null) ? ReviewImage.fromJson(json['image']) : null;
    evaluationApproveStatusId = json['evaluationApproveStatusId']?.toString();
    evaluationApproveStatus = (json['evaluationApproveStatus'] != null)
        ? ReviewEvaluationApproveStatus.fromJson(
            json['evaluationApproveStatus'])
        : null;
    if (json['productEvaluationImages'] != null) {
      final v = json['productEvaluationImages'];
      final arr0 = <ReviewProductEvaluationImages>[];
      v.forEach((v) {
        arr0.add(ReviewProductEvaluationImages.fromJson(v));
      });
      productEvaluationImages = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['description'] = description;
    data['productId'] = productId;
    data['product'] = product;
    data['rate'] = rate;
    data['userFullName'] = userFullName;
    data['created'] = created;
    data['createdDateTime'] = createdDateTime;
    data['createdSinceTime'] = createdSinceTime;
    data['imageId'] = imageId;
    if (image != null) {
      data['image'] = image!.toJson();
    }
    data['evaluationApproveStatusId'] = evaluationApproveStatusId;
    if (evaluationApproveStatus != null) {
      data['evaluationApproveStatus'] = evaluationApproveStatus!.toJson();
    }
    if (productEvaluationImages != null) {
      final v = productEvaluationImages;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['productEvaluationImages'] = arr0;
    }
    return data;
  }
}
