import 'package:sislimoda_admin_dashboard/models/product/product_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GetAnalysisModelTopSellingProductsProductDefaultPhoto {
/*
{
  "id": "a0c4fb82-f403-4809-928d-0ae09428a04d",
  "imageId": "91f4c87d-6540-46fe-83f4-bc90ed624968",
  "name": "91f4c87d-6540-46fe-83f4-bc90ed624968.jpg",
  "fullLink": "https://sislimoda.com/Files/91f4c87d-6540-46fe-83f4-bc90ed624968.jpg"
} 
*/

  String? id;
  String? imageId;
  String? name;
  String? fullLink;

  GetAnalysisModelTopSellingProductsProductDefaultPhoto({
    this.id,
    this.imageId,
    this.name,
    this.fullLink,
  });
  GetAnalysisModelTopSellingProductsProductDefaultPhoto.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    imageId = json['imageId']?.toString();
    name = json['name']?.toString();
    fullLink = json['fullLink']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['imageId'] = imageId;
    data['name'] = name;
    data['fullLink'] = fullLink;
    return data;
  }
}

class GetAnalysisModelTopSellingProductsProduct {
/*
{
  "id": "b63ceb4e-8492-446c-54dd-08dc3db67684",
  "name": " أديداس أوريجينالز",
  "nameEn": "Adidas Originals",
  "description": " أديداس أوريجينالز",
  "descriptionEn": "Adidas Originals",
  "defaultPrice": 100,
  "oldPrice": 0,
  "orderNUmber": 0,
  "htmlDescriptions": "string",
  "htmlOther": "string",
  "isActive": true,
  "defaultPhotoId": "a0c4fb82-f403-4809-928d-0ae09428a04d",
  "defaultPhoto": {
    "id": "a0c4fb82-f403-4809-928d-0ae09428a04d",
    "imageId": "91f4c87d-6540-46fe-83f4-bc90ed624968",
    "name": "91f4c87d-6540-46fe-83f4-bc90ed624968.jpg",
    "fullLink": "https://sislimoda.com/Files/91f4c87d-6540-46fe-83f4-bc90ed624968.jpg"
  },
  "categoryId": "56e0235c-532b-409f-8784-08dc1e165a43",
  "vendorId": "0fd4806d-e6e6-48df-7b91-08dc1ed95a1b",
  "amount": 50,
  "brandId": "ff6982b0-f2e8-47c6-0ed6-08dc1e1a7720",
  "brand": null,
  "paymentType": "string",
  "noteForReturn": "string",
  "created": "06-03-2024 18:32:50",
  "category": null,
  "productImages": [
    null
  ],
  "productOptions": [
    null
  ],
  "productDetails": [
    null
  ],
  "isFavourite": false,
  "productPrice": 0,
  "programDiscountPercentage": 0,
  "programDiscountValue": 0,
  "priceAfterProgramInfluencer": 0,
  "influencerPercentage": 0,
  "influencerValue": 0,
  "priceWithInfluencer": 0,
  "maxDiscountWithFamous": 0,
  "productDiscountPercentage": 0,
  "productDiscountValue": 0,
  "priceBeforeDiscount": 0,
  "maxProgramDiscountPercentage": 0,
  "finalDisplayPrice": 0,
  "offers": null,
  "discountPercentage": 0
}
*/

  String? id;
  String? name;
  String? nameEn;
  String? description;
  String? descriptionEn;
  String? defaultPrice;
  String? oldPrice;
  String? orderNUmber;
  String? htmlDescriptions;
  String? htmlOther;
  bool? isActive;
  String? defaultPhotoId;
  GetAnalysisModelTopSellingProductsProductDefaultPhoto? defaultPhoto;
  String? categoryId;
  String? vendorId;
  String? amount;
  String? brandId;
  String? brand;
  String? paymentType;
  String? noteForReturn;
  String? created;
  String? category;
  List<String?>? productImages;
  List<String?>? productOptions;
  List<String?>? productDetails;
  bool? isFavourite;
  String? productPrice;
  String? programDiscountPercentage;
  String? programDiscountValue;
  String? priceAfterProgramInfluencer;
  String? influencerPercentage;
  String? influencerValue;
  String? priceWithInfluencer;
  String? maxDiscountWithFamous;
  String? productDiscountPercentage;
  String? productDiscountValue;
  String? priceBeforeDiscount;
  String? maxProgramDiscountPercentage;
  String? finalDisplayPrice;
  String? offers;
  String? discountPercentage;

  GetAnalysisModelTopSellingProductsProduct({
    this.id,
    this.name,
    this.nameEn,
    this.description,
    this.descriptionEn,
    this.defaultPrice,
    this.oldPrice,
    this.orderNUmber,
    this.htmlDescriptions,
    this.htmlOther,
    this.isActive,
    this.defaultPhotoId,
    this.defaultPhoto,
    this.categoryId,
    this.vendorId,
    this.amount,
    this.brandId,
    this.brand,
    this.paymentType,
    this.noteForReturn,
    this.created,
    this.category,
    this.productImages,
    this.productOptions,
    this.productDetails,
    this.isFavourite,
    this.productPrice,
    this.programDiscountPercentage,
    this.programDiscountValue,
    this.priceAfterProgramInfluencer,
    this.influencerPercentage,
    this.influencerValue,
    this.priceWithInfluencer,
    this.maxDiscountWithFamous,
    this.productDiscountPercentage,
    this.productDiscountValue,
    this.priceBeforeDiscount,
    this.maxProgramDiscountPercentage,
    this.finalDisplayPrice,
    this.offers,
    this.discountPercentage,
  });
  GetAnalysisModelTopSellingProductsProduct.fromJson(
      Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    nameEn = json['nameEn']?.toString();
    description = json['description']?.toString();
    descriptionEn = json['descriptionEn']?.toString();
    defaultPrice = json['defaultPrice']?.toString();
    oldPrice = json['oldPrice']?.toString();
    orderNUmber = json['orderNUmber']?.toString();
    htmlDescriptions = json['htmlDescriptions']?.toString();
    htmlOther = json['htmlOther']?.toString();
    isActive = json['isActive'];
    defaultPhotoId = json['defaultPhotoId']?.toString();
    defaultPhoto = (json['defaultPhoto'] != null)
        ? GetAnalysisModelTopSellingProductsProductDefaultPhoto.fromJson(
            json['defaultPhoto'])
        : null;
    categoryId = json['categoryId']?.toString();
    vendorId = json['vendorId']?.toString();
    amount = json['amount']?.toString();
    brandId = json['brandId']?.toString();
    brand = json['brand']?.toString();
    paymentType = json['paymentType']?.toString();
    noteForReturn = json['noteForReturn']?.toString();
    created = json['created']?.toString();
    category = json['category']?.toString();

    isFavourite = json['isFavourite'];
    productPrice = json['productPrice']?.toString();
    programDiscountPercentage = json['programDiscountPercentage']?.toString();
    programDiscountValue = json['programDiscountValue']?.toString();
    priceAfterProgramInfluencer =
        json['priceAfterProgramInfluencer']?.toString();
    influencerPercentage = json['influencerPercentage']?.toString();
    influencerValue = json['influencerValue']?.toString();
    priceWithInfluencer = json['priceWithInfluencer']?.toString();
    maxDiscountWithFamous = json['maxDiscountWithFamous']?.toString();
    productDiscountPercentage = json['productDiscountPercentage']?.toString();
    productDiscountValue = json['productDiscountValue']?.toString();
    priceBeforeDiscount = json['priceBeforeDiscount']?.toString();
    maxProgramDiscountPercentage =
        json['maxProgramDiscountPercentage']?.toString();
    finalDisplayPrice = json['finalDisplayPrice']?.toString();
    offers = json['offers']?.toString();
    discountPercentage = json['discountPercentage']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['nameEn'] = nameEn;
    data['description'] = description;
    data['descriptionEn'] = descriptionEn;
    data['defaultPrice'] = defaultPrice;
    data['oldPrice'] = oldPrice;
    data['orderNUmber'] = orderNUmber;
    data['htmlDescriptions'] = htmlDescriptions;
    data['htmlOther'] = htmlOther;
    data['isActive'] = isActive;
    data['defaultPhotoId'] = defaultPhotoId;
    if (defaultPhoto != null) {
      data['defaultPhoto'] = defaultPhoto!.toJson();
    }
    data['categoryId'] = categoryId;
    data['vendorId'] = vendorId;
    data['amount'] = amount;
    data['brandId'] = brandId;
    data['brand'] = brand;
    data['paymentType'] = paymentType;
    data['noteForReturn'] = noteForReturn;
    data['created'] = created;
    data['category'] = category;

    data['isFavourite'] = isFavourite;
    data['productPrice'] = productPrice;
    data['programDiscountPercentage'] = programDiscountPercentage;
    data['programDiscountValue'] = programDiscountValue;
    data['priceAfterProgramInfluencer'] = priceAfterProgramInfluencer;
    data['influencerPercentage'] = influencerPercentage;
    data['influencerValue'] = influencerValue;
    data['priceWithInfluencer'] = priceWithInfluencer;
    data['maxDiscountWithFamous'] = maxDiscountWithFamous;
    data['productDiscountPercentage'] = productDiscountPercentage;
    data['productDiscountValue'] = productDiscountValue;
    data['priceBeforeDiscount'] = priceBeforeDiscount;
    data['maxProgramDiscountPercentage'] = maxProgramDiscountPercentage;
    data['finalDisplayPrice'] = finalDisplayPrice;
    data['offers'] = offers;
    data['discountPercentage'] = discountPercentage;
    return data;
  }
}

class GetAnalysisModelTopSellingProducts {
/*
{
  "productId": "b63ceb4e-8492-446c-54dd-08dc3db67684",
  "product": {
    "id": "b63ceb4e-8492-446c-54dd-08dc3db67684",
    "name": " أديداس أوريجينالز",
    "nameEn": "Adidas Originals",
    "description": " أديداس أوريجينالز",
    "descriptionEn": "Adidas Originals",
    "defaultPrice": 100,
    "oldPrice": 0,
    "orderNUmber": 0,
    "htmlDescriptions": "string",
    "htmlOther": "string",
    "isActive": true,
    "defaultPhotoId": "a0c4fb82-f403-4809-928d-0ae09428a04d",
    "defaultPhoto": {
      "id": "a0c4fb82-f403-4809-928d-0ae09428a04d",
      "imageId": "91f4c87d-6540-46fe-83f4-bc90ed624968",
      "name": "91f4c87d-6540-46fe-83f4-bc90ed624968.jpg",
      "fullLink": "https://sislimoda.com/Files/91f4c87d-6540-46fe-83f4-bc90ed624968.jpg"
    },
    "categoryId": "56e0235c-532b-409f-8784-08dc1e165a43",
    "vendorId": "0fd4806d-e6e6-48df-7b91-08dc1ed95a1b",
    "amount": 50,
    "brandId": "ff6982b0-f2e8-47c6-0ed6-08dc1e1a7720",
    "brand": null,
    "paymentType": "string",
    "noteForReturn": "string",
    "created": "06-03-2024 18:32:50",
    "category": null,
    "productImages": [
      null
    ],
    "productOptions": [
      null
    ],
    "productDetails": [
      null
    ],
    "isFavourite": false,
    "productPrice": 0,
    "programDiscountPercentage": 0,
    "programDiscountValue": 0,
    "priceAfterProgramInfluencer": 0,
    "influencerPercentage": 0,
    "influencerValue": 0,
    "priceWithInfluencer": 0,
    "maxDiscountWithFamous": 0,
    "productDiscountPercentage": 0,
    "productDiscountValue": 0,
    "priceBeforeDiscount": 0,
    "maxProgramDiscountPercentage": 0,
    "finalDisplayPrice": 0,
    "offers": null,
    "discountPercentage": 0
  },
  "totalSales": 44
}
*/

  String? productId;
  ProductModel? product;
  String? totalSales;

  GetAnalysisModelTopSellingProducts({
    this.productId,
    this.product,
    this.totalSales,
  });
  GetAnalysisModelTopSellingProducts.fromJson(Map<String, dynamic> json) {
    productId = json['productId']?.toString();
    product = (json['product'] != null)
        ? ProductModel.fromJson(json['product'])
        : null;
    totalSales = json['totalSales']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['productId'] = productId;
    if (product != null) {
      data['product'] = product!.toJson();
    }
    data['totalSales'] = totalSales;
    return data;
  }
}

class GetAnalysisModel {
/*
{
  "totalCategoryAndSubCategory": 74,
  "totalOrders": 19,
  "totalProducts": 16,
  "numberOfVendors": 10,
  "topSellingProducts": [
    {
      "productId": "b63ceb4e-8492-446c-54dd-08dc3db67684",
      "product": {
        "id": "b63ceb4e-8492-446c-54dd-08dc3db67684",
        "name": " أديداس أوريجينالز",
        "nameEn": "Adidas Originals",
        "description": " أديداس أوريجينالز",
        "descriptionEn": "Adidas Originals",
        "defaultPrice": 100,
        "oldPrice": 0,
        "orderNUmber": 0,
        "htmlDescriptions": "string",
        "htmlOther": "string",
        "isActive": true,
        "defaultPhotoId": "a0c4fb82-f403-4809-928d-0ae09428a04d",
        "defaultPhoto": {
          "id": "a0c4fb82-f403-4809-928d-0ae09428a04d",
          "imageId": "91f4c87d-6540-46fe-83f4-bc90ed624968",
          "name": "91f4c87d-6540-46fe-83f4-bc90ed624968.jpg",
          "fullLink": "https://sislimoda.com/Files/91f4c87d-6540-46fe-83f4-bc90ed624968.jpg"
        },
        "categoryId": "56e0235c-532b-409f-8784-08dc1e165a43",
        "vendorId": "0fd4806d-e6e6-48df-7b91-08dc1ed95a1b",
        "amount": 50,
        "brandId": "ff6982b0-f2e8-47c6-0ed6-08dc1e1a7720",
        "brand": null,
        "paymentType": "string",
        "noteForReturn": "string",
        "created": "06-03-2024 18:32:50",
        "category": null,
        "productImages": [
          null
        ],
        "productOptions": [
          null
        ],
        "productDetails": [
          null
        ],
        "isFavourite": false,
        "productPrice": 0,
        "programDiscountPercentage": 0,
        "programDiscountValue": 0,
        "priceAfterProgramInfluencer": 0,
        "influencerPercentage": 0,
        "influencerValue": 0,
        "priceWithInfluencer": 0,
        "maxDiscountWithFamous": 0,
        "productDiscountPercentage": 0,
        "productDiscountValue": 0,
        "priceBeforeDiscount": 0,
        "maxProgramDiscountPercentage": 0,
        "finalDisplayPrice": 0,
        "offers": null,
        "discountPercentage": 0
      },
      "totalSales": 44
    }
  ],
  "numberOfOffers": 4
}
*/

  String? totalCategoryAndSubCategory;
  String? totalOrders;
  String? totalProducts;
  String? numberOfVendors;
  List<GetAnalysisModelTopSellingProducts?>? topSellingProducts;
  String? numberOfOffers;
  String? totalSoldProducts;
  String? totalRevenue;
  String? totalProduct;

  GetAnalysisModel({
    this.totalCategoryAndSubCategory,
    this.totalOrders,
    this.totalProducts,
    this.numberOfVendors,
    this.topSellingProducts,
    this.numberOfOffers,
  });
  GetAnalysisModel.fromJson(Map<String, dynamic> json) {
    totalCategoryAndSubCategory =
        json['totalCategoryAndSubCategory']?.toString();
    totalOrders = json['totalOrders']?.toString();
    totalProducts = json['totalProducts']?.toString();
    numberOfVendors = json['numberOfVendors']?.toString();
    totalSoldProducts = json['totalSoldProducts']?.toString();
    totalRevenue = json['totalRevenue']?.toString();
    totalProduct = json['totalProduct']?.toString();
    if (json['topSellingProducts'] != null) {
      final v = json['topSellingProducts'];
      final arr0 = <GetAnalysisModelTopSellingProducts>[];
      v.forEach((v) {
        arr0.add(GetAnalysisModelTopSellingProducts.fromJson(v));
      });
      topSellingProducts = arr0;
    }
    numberOfOffers = json['numberOfOffers']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['totalCategoryAndSubCategory'] = totalCategoryAndSubCategory;
    data['totalOrders'] = totalOrders;
    data['totalProducts'] = totalProducts;
    data['numberOfVendors'] = numberOfVendors;
    if (topSellingProducts != null) {
      final v = topSellingProducts;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['topSellingProducts'] = arr0;
    }
    data['numberOfOffers'] = numberOfOffers;
    return data;
  }
}
